### ISSUE TITLE
Cant fill in particular config value in OZW addon

### ISSUE THREAD

**Issue by nelbs** [home-assistant/addons#1600]
## The problem

I have some Neo coolcam PIR PD02Z sensors and are unable to change parameter 99 (ambient light intensity calibration) . In the OZW addon I cant fill in / change  a number at the entry of parameter 99. When I try this via the ozw.set_config_parameter I get some errors in HA log and OZW addon log. 
The ozw log doesn't show no errors / warnings.

The strange thing is that the initial value is 1000. When I click on that value to change it, it changes automatically to 1. Then I cant change it anymore.

I checked the xml file but i dont see something strange

![image](https://user-images.githubusercontent.com/6464671/94433579-d1b6b180-0198-11eb-8bfa-7dbeddb8f1bd.png)
![image](https://user-images.githubusercontent.com/6464671/94433982-5f929c80-0199-11eb-883f-3e4bf266abd3.png)

## Environment

- Add-on with the issue: OpenZwave
- Add-on release with the issue:  0.5.2
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  Supervised
- Aeotec gen 5 stick + NEO coolccam PIR V2 (PD02Z)

## Problem-relevant configuration

```
device: /dev/serial/by-id/usb-0658_0200-if00
network_key: >-
xxxx xxxx xxxx

```

## Traceback/Error logs

HA message when using calling ozw.set_config_parameter
```
Kan service ozw/set_config_parameter niet aanroepen 'NoneType' object has no attribute 'type'
```
Message in OZW addon log
```
[20200928 14:57:02.654 CEST] [default] [debug]: QVariant(int, 5) 
[20200928 14:57:02.656 CEST] [default] [debug]: QVariant(int, 14) 
[20200928 14:57:02.656 CEST] [default] [debug]: QVariant(int, 1) 
[20200928 14:57:02.657 CEST] [default] [debug]: QVariant(int, 3) 
[20200928 14:57:02.658 CEST] [default] [debug]: QVariant(int, 12) 
[20200928 14:57:02.659 CEST] [default] [debug]: QVariant(int, 4) 
[20200928 14:57:02.660 CEST] [default] [debug]: QVariant(int, 16) 
[20200928 14:57:02.661 CEST] [default] [debug]: QVariant(int, 17) 

```

**Comment by kpine** [comment]
There are various problems setting values in ozw-admin, for example: https://github.com/OpenZWave/ozw-admin/issues/33.

The problem with `set_config_parameter` and `short` values was fixed in HA 0.115. What version are you using?

**Comment by nelbs** [comment]
Hi, I am using version 0.115.6

**Comment by kpine** [comment]
What is the service data you are using?

**Comment by kpine** [comment]
Another question, what Stage is your node in? You can find this in the UI, Configuration -> Devices. Select this device and the Device Info will list the Stage.

**Comment by nelbs** [comment]
The stage of this node is complete and this is the service data:

```
node_id: 14
parameter: 99
value: 1000
```

**Comment by kpine** [comment]
> `Kan service ozw/set_config_parameter niet aanroepen 'NoneType' object has no attribute 'type'`

I am guessing that you are running into the same problem that [this PR](https://github.com/cgarwood/python-openzwave-mqtt/pull/98) was attempting to fix. Until that problem is fixed in the upstream library you won't be able to use Home Assistant to change the value.

There also looks to be a bug in the [device XML](https://github.com/OpenZWave/open-zwave/blob/b0afd4c60b38065fdbc57835cb3eb6035afcc00f/config/shenzen_neo/nas-pd02z.xml#L105) definition for parameter 99. This error is likely causing the ozw-admin GUI to be unable to configure the value correctly.

```xml
    <Value type="short" genre="config" instance="1" index="99" label="Ambient Light Intensity Calibration" value="1000" min="1" max="65536" size="2">
```
The type is a "short" with size "2", but the maximum value is set 65536. OZW represents "short" values as signed 16-bit integers. The maximum value is in fact 32767. A value of 65536 when casted to a short maps to 0, which is why ozw-admin won't let you change the value. This would also affect HA since it checks the min and max.

If the device really does allow a value up to 65535 (0xffff), then to allow the full range of values, you'd need to modify the XML file to:
```xml
    <Value type="short" genre="config" instance="1" index="99" label="Ambient Light Intensity Calibration" value="1000" min="-32768" max="32767" size="2">
```
You cannot exclude the value 0. But this configuration parameter is [undocumented](https://github.com/OpenZWave/open-zwave/issues/1866), and there appear to be different versions of the product, so who knows what it's supposed to be.

You can bypass HA and ozw-admin and set the value directly via MQTT using the [`setvalue`](https://github.com/OpenZWave/qt-openzwave/blob/master/docs/MQTT.md#setvalue) command. Use MQTT Explorer to find the value id key. Use MQTT explorer to publish the command.

topic: `OpenZWave/1/command/setvalue/`
payload:
```json
{
  "ValueIDKey": 123456789,
  "Value": 300
}
```

Replace `123456789` with your key.

**Comment by nelbs** [comment]
> If the device really does allow a value up to 65535 (0xffff), then to allow the full range of values, you'd need to modify the XML file to:
> 
> ```
>     <Value type="short" genre="config" instance="1" index="99" label="Ambient Light Intensity Calibration" value="1000" min="-32768" max="32767" size="2">
> ```

thanks @kpine that did the trick. Now I can change the value in the OZW gui. 

Very useful program, mqtt explorer. I did not know that.

**Comment by jasonpstokes** [comment]
> You can bypass HA and ozw-admin and set the value directly via MQTT using the [`setvalue`](https://github.com/OpenZWave/qt-openzwave/blob/master/docs/MQTT.md#setvalue) command. Use MQTT Explorer to find the value id key. Use MQTT explorer to publish the command.
> 
> topic: `OpenZWave/1/command/setvalue/`
> payload:
> 
> ```json
> {
>   "ValueIDKey": 123456789,
>   "Value": 300
> }
> ```
> 
> Replace `123456789` with your key.

How do I find the ValueIDKey for parameters 111-113 in MQTT explorer please?
  ![image](https://user-images.githubusercontent.com/29766924/100276505-c673dc80-2fb5-11eb-8af6-c120876ba973.png)

Plus I also can not see OpenZWave/<instance>/command/ ?
  ![image](https://user-images.githubusercontent.com/29766924/100276396-92002080-2fb5-11eb-9c2d-305681f0929b.png)

Background: I have the same issue as nelbs, but with two Aeotec Smart Switch 6's (ZW096). Parameters 111 - 113 are the reporting intervals for the switch (in seconds), but OpenZWave WebUI will not set them to anything but zero - which disables reporting. Running HA 118.3 and OpenZWave add-on 0.7.1

Thanks...
