### ISSUE TITLE
Reopen issue #224

### ISSUE THREAD

**Issue by mattclar** [home-assistant/addons#1666]
@pvizeli  Please reopen issue home-assistant/operating-system#224 
There is active issues from multiple users but it was closed by the stale-bot :/

**Comment by ygreq** [comment]
I tried reinstalling this and it is working for me now. No issues

**Comment by ludeeus** [comment]
This and the issue that it's pointed to is so messy, with all sorts of different cases.
Can someone that still experiences "this?" open a new issue and fill out the issue template?
https://github.com/home-assistant/addons/issues/new?template=BUG_REPORT.md

**Comment by fotodille** [comment]
I found this to be a functioning solution to the same issue on my RPi3 with OS 5.9 and HomeAssistant 2020.12.1 and Supervisor 2020.12.7:
https://community.home-assistant.io/t/hassio-supervisor-cannot-connect-to-host-172-30-32-1-8123-ssl-none-connection-refused/135327/20?u=fotodille

Maybe the posts prior to that one will clarify for developers what the problem is. I'm not at all into docker myself so I can't tell for sure, but it looked reasonable to me.
