### ISSUE TITLE
After upgrade to deCONZ 6.5 the phoscon web app does not work any more

### ISSUE THREAD

**Issue by Beiri22** [home-assistant/addons#1677]
I click on deconz / phoscon. Normally it would launch the login dialog and after login the web app.
Now there is just the phoscon logo at the top. When I click onto it, a loading screen starts: "Bitte warten, während die Suche nach Gateways durchgeführt wird." --> Wait while looking for gateways. That's it. No more.

The other deconz-VNC-App seems to work.

**Comment by wovka88** [comment]
I have the Conbee 2 with Firmware 0x26660700, everything works fine..

Maybe a Cache-Problem? Is the Problem in all browsers? Which stick do you have?

**Comment by Beiri22** [comment]
I have also a Conbee 2 with Firmware 0x26660700
The problem happens in Google Chrome and the HA-App. I've not tried firefox.
I tried to clean the cache, no change.

[problem.webm.zip](https://github.com/home-assistant/hassio-addons/files/5546024/problem.webm.zip)

**Comment by pawlizio** [comment]
I've the same issue with my RPi4B. Actually I was trying to change from Raspian OS to HassOS, but with the Hassio Addon I'm not able to use Phoscon. The VNC monitor shows all devices, but in order to install the backup which I created on Raspian OS, I need access to Phoscon App. However the Phoscon App does not show the Login section, only the Logo as described above.

If I change back the SD card to the one with Raspian everything is fine. 

On Raspian I checked the Phoscon Version and Firmware:
```
Version 2.05.78 5/22/2020
Firmware 26390500
```

**Comment by Puntoboy** [comment]
Not sure if this is related but since I upgraded to the latest version a few days ago I consistently get timeouts within the web app. 

![image](https://user-images.githubusercontent.com/11718878/102700763-5836d880-4248-11eb-9b21-ce18df61703b.jpeg)

I've also noticed that Node-Red is constantly trying to reconnect to Deconz and the devices are responding very slowly. 

![image](https://user-images.githubusercontent.com/11718878/102700741-2de51b00-4248-11eb-8347-2f9ee7d65a45.png)

I've also seen several German words in the UI suddenly. 

![image](https://user-images.githubusercontent.com/11718878/102700669-6df7ce00-4247-11eb-8452-c39fa56afb33.png)

**Comment by pawlizio** [comment]
Any solution, I bought additionally to my RaspBee I a Conbee II. 
I started with a clean HassOS, just created an account, installed the official AddOn and have still the same issue.

With my Raspbian SD image where I installed Deconz directly everything works fine with both RaspBee I and Conbee II.

**Comment by pawlizio** [comment]
I identified now my problem. I use a reverse proxy to access to my homeassistant through the internet. That reverse proxy only redirects my main port of HA, so all the Ingress stuff is not working if I call it through my domain. Phoscon was working immediately if tried to access HA via local IP. Sorry for disturbing! But maybe other people here have the same issue.

**Comment by Beiri22** [comment]
Oh. I tried the same, it was accessable via the local IP. But I have thought, that all the access to the internal API is routet locally. So I connect to my remote ip, and home assist uses local access to deconz... Is that not so?

**Comment by pawlizio** [comment]
This issue is the same as #947
