### ISSUE TITLE
Mosquitto Addon is based on outdated / unmaintained software

### ISSUE THREAD

**Issue by kbabioch** [home-assistant/addons#1734]
## The problem

The latest version of the mosquitto addon (`addons/mosquitto`) is based on an old version of mosquitto (1.6.3). Additionally an authentication plugin is used, that is no longer maintained in the original repository: https://github.com/pvizeli/mosquitto-auth-plug 

In the meantime the mosquitto 2.0 series has been released, with 2.0.4 being released on 2020-12-22. The 2.0 series improves security (by dropping privileges, etc.). Also it allows for dynamic security plugins, which allow for clients and roles to be defined during runtime. This will probably make the usage of the unmaintained authentication plugin obsolete.

## Environment

- Add-on with the issue: addons/mosquitto/
- Add-on release with the issue: 5.1
- Last working add-on release (if known): None
- Operating environment (OS/Supervised): OS

## Additional information

While this seems to be not too important right away, a migration to this version is still advisable.

Also it will make sure that an smooth and easy upgrade path is ready and in place. If a security vulnerability is only fixed in 2.0.x, it will be tricky to get it upgraded otherwise. Better to do this in a planned and tested environment, than to rush out an update to the community later on, fixing their MQTT setups.

**Comment by frenck** [comment]
Your issue is incorrect.

Mosquitto 2.x has not been adopted by Alpine Linux yet, the latest version available is 1.6.12, which is currently considered edge (thus not stable).

The used auth plugin is a fork of the abandoned version. The fork is maintained and in working condition. I guess you've been misled by the message from the original author.

The 2.0 security features for e.g., dropping privileges, won't add much as the add-on already runs in an isolated environment.

All in all, this issue is a feature request, for which we use our community forums.

Thanks! 👍

Happy Holidays!
