### ISSUE TITLE
Information about Homematic Docker

### ISSUE THREAD

**Issue by sim-san** [home-assistant/addons#1751]
## The problem

This not a bug. I just want to mention that the community at the [jens-maus/RaspberryMatic](https://github.com/jens-maus/RaspberryMatic) project works on a docker integration. They have completed the first version and are now in the test stage. Here are the related issues and PR:

- https://github.com/jens-maus/RaspberryMatic/issues/786
- https://github.com/jens-maus/RaspberryMatic/pull/1056

Maybee this can help or make updating easier...

## Environment

- Add-on with the issue: /
- Add-on release with the issue: /
- Last working add-on release (if known): /
- Operating environment (OS/Supervised): /

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by nicx** [comment]
I am ready for testing :)

**Comment by jens-maus** [comment]
Nice to see the home-assistant community to recognize the recent docker activities in the RaspberryMatic project so fast. 👍 

Please note, that I have planned to look into home-assistant integration of the new RaspberryMatic docker in the near future myself. My plan would be to generate a dedicated RaspberryMatic home-assistant addon at some point and directly distribute it over the RaspberryMatic GitHub project. In addition, I will see if changes can be integrated to the home-assistant/operating-system project as well, because for the RaspberryMatic docker to work correctly changes are required regarding introducing the necessary kernel modules on the host system to work with the homematic rf modules available.

**Comment by feutl** [comment]
For everyone who is watching this, should also have a look at https://github.com/home-assistant/operating-system/pull/1266 and support this endeavor

**Comment by frenck** [comment]
This is not a bug and not related to the add-ons, thus closing the issue on this end.

Thanks 👍
