### ISSUE TITLE
New firmware missing from Add On for Eurotronic Spirit Zigbee thermostat

### ISSUE THREAD

**Issue by fribse** [home-assistant/addons#1787]
## The problem

Firmware for Spirit Zigbee thermostat is missing from the add-on.

## Environment

- Add-on with the issue: deconz
- Add-on release with the issue: 6.6.2
- Last working add-on release (if known): New firmware, so not previously available
- Operating environment (OS/Supervised):  Supervised

## Problem-relevant configuration

From the Deconz page you can select updates for the devices, but the new firmware for Eurotronic is not available (https://github.com/EUROTRONIC-Technology/Spirit-ZigBee).
Not so much a bug, but a missing file.
I can't find a way to add the OTA file myself to the Deconz addon.

```

## Traceback/Error logs
<!--
  If you come across any trace or error logs, please provide them.
-->

```txt

```

**Comment by fribse** [comment]
Ahaa, I finally figured it out, I have to use the community addon of ssh, and not the official one to get the docker cp to work.
After doing that the file has been copied into my deconz, and I can start updating my thermostats.

**Comment by Marlor** [comment]
@fribse can you please explain how you did it?

**Comment by double1968** [comment]
I use Hassio, I copied the file to the docker folder via ssh.
I can't update. After selecting the file the device is IDLE, I press update, nothing happens!?

**Comment by fribse** [comment]
@Marlor I used the Community SSH addon (the official one). I copied the file to the samba 'share' on the home-assistant from my pc.

I then did
![image](https://user-images.githubusercontent.com/13660621/106379383-e3f56600-63ab-11eb-85f4-79014efeea40.png)

I couldn't make this work via the official SSH addon, didn't have the docker command, and couldn't log in from the prompt.

@double1968 From the deconz interface, I open the OTAU panel, I then found the thermostat in the map, clicked basic and read, just to wake it up. It is then also highlighted in the list in the OTAU panel, I selected the file in the OTAU panel, pressed query, it showed idle, and then I pressed update, sometimes I had to press it twice, and then within a minutte or so, it started showing a progress %, took about two hours per thermostat, and I didn't want to update them all at the same time.
![image](https://user-images.githubusercontent.com/13660621/106379498-b52bbf80-63ac-11eb-8053-e59d17b23fae.png)

**Comment by WolfRevo** [comment]
As this is an old firmware version that can be used as intermediate solution for already corrupted Spirit Zigbee devices I don't see why it should be available in deCONZ. The same git repo clearly states that a new firmware released by Eurotronic is planned for the future but a new employee won't start working on issues and the firmware itself prior to March 2021. So I recommend to close this issue as it misleads that there is a "new" firmware for the Eurotronic Spirit Zigbee available.

**Comment by fribse** [comment]
@WolfRevo As it clearly has an older date, I doubt that it will be presented as a new firmware? But it will definetely ease peoples downgrading if it's in there from the beginning.

**Comment by Marlor** [comment]
> 
> 
> As this is an old firmware version that can be used as intermediate solution for already corrupted Spirit Zigbee devices I don't see why it should be available in deCONZ.

20190408 is the newest bugfree version available, everyone who can should probably up/downgrade.

Up until now i seen these versions:

20181205
20190408
20191014 with is buggy
20191014 with broken reporting that cannot be downgraded

**Comment by WolfRevo** [comment]
@fribse @Marlor can you please provide some links/evidence for your statement that version 20190408 is bugfree? I have 6 thermostats running 20191014 (looks like not the broken one as I don't have connection issues). I would love to know the functional difference between the old 20190408 and the 'buggy' 20191014.
I just wanted to say that I think (so only my personal opinion for sure) it makes more sense to wait for a new release which adresses the most important issues. But if it is clear that 20190408 is ready for release due to no known bugs and there is a good documented way to downgrade to that firmware than it could be for sure added to the deCONZ addon (if it works for the 'normal' user easily).

**Comment by fribse** [comment]
I have moved all my (well functioning) thermostats to the old firmware, and have seen an increase in stability, especially in battery change situations. But I still don't understand the resentment, and why the possibility for easy downgrade is a problem. It will not just do it automagically, but not all knows how to upload the file to the add-on.
The downgrade procedure is simple, and is described in the github.

**Comment by Marlor** [comment]
@WolfRevo The one thermostat i could downgrade from 20191014 to 20190408 is now reporting the temperature in 0.1 degree steps insted of 0.5 and it is using less motor movement while holding the same temperature.

**Comment by WolfRevo** [comment]
I can't speak for the developer and I don't have any decision responsibility so don't get me wrong ;) proposals are only my personal view.

As I have one out of 7 thermostats that behaves strange also (I never realized it did so far as it is used in a room where we usually don't use the heater) and I don't get it working well (it just ignores 80% of any heatpoint settings besides it is online and reports it's values correct to deCONZ) I'll give it a try and downgrade this one to the 20190408 version. I will come back with my observations.

**Comment by WolfRevo** [comment]
I had time to downgrade all of my thermostats. Observations after one week:
6 out 7 used thermostats work as before, no obvisious difference (20191014 firmware before but not the one which can't be downgraded). Number 7 behaved as strange as before (also the same firmware before and after, no obvisious difference). I digged deeper and I am still not finished. I needed to complete remove it from deCONZ and register it again. Still in observation due to the fact that these thermostats have at least a uncool "feature": they acknowledge any commands sent from deCONZ positively ignoring if the thermostat did really accept the command internally. So if you send a temperature change first and very short after an 'off' command the thermostat might be still closing it's valve. deCONZ shows that the thermostat is 'off' (you can see in the logs that the thermostat reports that state) and if you look on the thermostat it's still in mode 'auto'. The next time the thermostat reports it's regular status update it's again 'auto' in deCONZ as well. You need to wait long enough between two commands to be sure it is really successful. 30 seconds worked for me in any case so far but as I said I am still observing.
