### ISSUE TITLE
vlc addon no info with credentials.  it is impossible to add to HA

### ISSUE THREAD

**Issue by shirou93** [home-assistant/addons#1898]
## The problem

Addon start but no showing up in discovery and in config only audio source. No credentials.

## Environment

- Add-on with the issue: vlc addon
- Add-on release with the issue:   0.1.2 
- Last working add-on release (if known): ??
- Operating environment (OS/Supervised): Debian 10

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by realthk** [comment]
Not impossible, but not straightforward indeed. I don't know, why there isn't any instruction in the Documentation tab of this addon what to enter (what password and IP) under platform: vlc_telnet.

Checking the content of this add-on, it seems it generates its password into /data/secret (which is required in configuration.yaml)
So first step was to get the content of it:

```
docker exec -it addon_core_vlc /bin/bash
cat /data/secret
```

Then I tried the IP address of my HA host, but it did not work, `media_player.vlc` was in unavailable state. I checked the address of VLC docker with `docker inspect addon_core_vlc  | grep IPAddress` command, which happened to be 172.30.33.16 in my case. Not sure if its right for the long run (don't know if it can change) but have no better idea now.

So finally this is what my configuration.yaml has now, which resulted `media_player.vlc` entity in idle state (has no speaker attached to it yet, but I guess it will work)

```
media_player:
  - platform: vlc_telnet
    name: VLC
    host: 172.30.33.16
    port: 4212
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

```

**Comment by shirou93** [comment]
@realthk  works thanks. In host you can add " host: 'core-vlc'" without ip.

Password should be in logs or config.

**Comment by baerni** [comment]
How to check the password on Raspberry Pi and Home Assistant Operating System without Debian or Raspbian?

**Comment by shirou93** [comment]
> How to check the password on Raspberry Pi and Home Assistant Operating System without Debian or Raspbian?

Propably addon portainer and turn on console container on web panel.

**Comment by tofuSCHNITZEL** [comment]
indeed currently its not very straight forward to use this addon properly... the generated secret is not displayed in the logs and the secret is nowhere to be found inside the "config" folder. (home assistant os)
According to this file:
https://github.com/home-assistant/addons/blob/master/vlc/rootfs/etc/services.d/vlc/discovery
the addon is sending a discovery (containing the secret) to HA and it also prints the "successful" message in the logs - there is even a "VLC" device in the registry with 3 unavailable items... but no media player. (yes even after a HA restart)

I also had to enable supervisor ssh for homeassistant os to ssh and use the docker exec command to go into the vlc container to get the secret... 

@pvizeli could you shed some light on this? what is the discovery message for? should it create the vlc_telnet mediaplayer for us? why is the port ^3000 should it not be  4241?

I think the discovery only works if the home assistant component contains a config flow... since I also have these error messages in the log:
` Error occurred loading configuration flow for integration vlc_telnet: No module named 'homeassistant.components.vlc_telnet.config_flow' `

so I guess the vlc_telnet component needs to get a config flow first

**Comment by 2yongbum** [comment]
Here is configuration for VLC add-on.
https://github.com/home-assistant/addons/blob/master/vlc/DOCS.md 
```
media_player:
  - platform: vlc_telnet
    name: VLC Player
    host: core-vlc
    port: 4212
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
password can be seen by installing Portainer add-on and execute console of addon_core_vlc then
```
cat /data/secrete
```

**Comment by hdlineage** [comment]
There should definitely be an easier to get/set the password.
A better documentation would also be appreciated.

**Comment by shirou93** [comment]
Still no updated, official addon shuld be easier to use. Password shuld be appear on config or logs.

**Comment by neckyaan** [comment]
[00007f9c7f1a3d50] main audio output error: module not functional
[00007f9c7a4df780] main decoder error: failed to create audio output
[00007f9c7f1a3d50] vlcpulse audio output error: stream connection failure: No such entity
