### ISSUE TITLE
File Editor add-on "unknown tag !<!input>" in Blueprint.

### ISSUE THREAD

**Issue by wizvvs** [home-assistant/addons#1907]
## The problem
File Editor add-on reports error "unknown tag !<!input>... " in the blueprint when try to write configurable parts as inputs.

## Environment
Add-on: File Editor
Current version: 5.2.0
Operating environment: Supervised 

## Traceback/Error logs
```
unknown tag !<!input> at line 14, column 34:
      entity_id: !input target_device
                                     ^
```

**Comment by frenck** [comment]
Hi there @wizvvs!

Thanks for opening an issue, however, add-ons wrap existing applications, in this case: the `hass-configurator`.

The issue is with the application that this add-on wraps. Please report your issue upstream here:
<https://github.com/danielperna84/hass-configurator/>

Once it is fixed upstream, we can update the add-on to distribute the fixed file editor version.

From an add-on perspective, there is nothing we can do.
