### ISSUE TITLE
Z-Wave JS 0.1.14 Makes CT100 Thermostat Climate Entity Unavailable

### ISSUE THREAD

**Issue by keithcroshaw** [home-assistant/addons#1943]
## The problem

A few updates back something similar happened where after the update the climate entity was unavailable. Now the CT100 Z-Wave thermostat climate entity is unavailable after the 0.1.14 update again. A snapshot rollback returned it to operational.

## Environment

- Add-on with the issue: Z-Wave JS
- Add-on release with the issue: 0.1.14
- Last working add-on release (if known): 0.1.13
- Operating environment (OS/Supervised): Home Assistant OS 5.12

## Problem-relevant configuration

```yaml
UI Driven. CT100 was added via UI Configuration a while ago.
```

## Traceback/Error logs

```txt
2021-03-26T12:23:33.944Z CNTRLR   [Node 018] The node is alive.
2021-03-26T12:23:33.944Z CNTRLR   [Node 018] The node is ready to be used
2021-03-26T12:23:33.944Z CNTRLR   All nodes are ready to be used
2021-03-26T12:23:33.945Z CNTRLR « [Node 018] ping successful

Node 18 is the CT100 Thermostat, it seems to think it's fine.
```

**Comment by Indianb0y016** [comment]
So Ill leave some info here. It happened to me with a CT101 and a CT100. Both entities were considered unavailable, and two more climate entities were created in the device tree, each. All four climate entities are bugged however. From my forum post, the developer behind the backwards compatibility layer is aware of the issue and currently investigating the problem.

**Comment by keithcroshaw** [comment]
Thanks, I'm often told to bring it up here and not the forum, so here's my first.
Thanks @MartinHjelmare for tagging it and @Indianb0y016 for the info.

**Comment by Indianb0y016** [comment]
Well, my forum post was not merely me posting about the issue but rather warning others not to update to the latest addon version. I didnt post a github issue because Im still getting used to github and I didnt want to post an incomplete issue that creates clutter so I let it be. I will inform you that a temporary solution to this is to switch to the Zwavejstomqtt addon. Im not having any issues with that so far. Though my node list is small so its not too much of a pain to switch back and forth, but for some folks, that can be a headache. Im thinking the solution to this will be when home assistant core is updated in April.

**Comment by MartinHjelmare** [comment]
Is this still an issue, on latest Home Assistant and zwave-js server version?

**Comment by keithcroshaw** [comment]
No it was fixed the version after I reported the issue. Thank you.
