### ISSUE TITLE
Configurator/File-Editor push is not working if new configured

### ISSUE THREAD

**Issue by roterBulle** [home-assistant/addons#1999]
## The problem

  I Installed the File-Editor addon and tried to push to my github repo. Unfortunately this was not working and throwing the following error:
 Could not read from remote repository ! Please make sure you have the correct access rights. 

I could workaround the issue by ssh'ing into the  container and executing git push from there. On console there was a question for accepting the fingerprint of the github server and afterwards it also worked in UI!
![image](https://user-images.githubusercontent.com/7093321/117439499-327a4980-af33-11eb-92ae-0a4037b6d90a.png)

## Environment

- Add-on with the issue: File editor
- Add-on release with the issue: 5.3.0
- Last working add-on release (if known): nA
- Operating environment (OS/Supervised):  Supervised

## Problem-relevant configuration

```dirsfirst: false
enforce_basepath: true
git: true
ignore_pattern:
  - __pycache__
  - .cloud
  - .storage
  - deps
ssh_keys:
  - /config/.ssh/id_rsa

```

## Traceback/Error logs

```
INFO:2021-05-07 12:39:17,926:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2021-05-07 12:39:32,553:hass_configurator.configurator:172.30.32.2 - "GET /api/file?filename=/config/automations.yaml HTTP/1.1" 200 -
WARNING:2021-05-07 12:39:39,502:hass_configurator.configurator:{'error': True, 'message': "Cmd('git') failed due to: exit code(128)\n  cmdline: git push --porcelain origin\n  stderr: 'fatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.'", 'path': '/config'}

```
## Maybe this is how it can be fixed:
https://unix.stackexchange.com/questions/18853/answer-yes-in-a-bash-script
Add the following to your ~/.ssh/config file:

Host github.com
    StrictHostKeyChecking no

Unfortunately i am not able to fix it as i am not experienced with Docker containers

**Comment by d-vdh** [comment]
i just came across my own issue, because i still had it. 
This issue is still present. 

But i managed with some years of more experience to enter the command line in the container. 
Steps to logon to the container:
1. Disable protection mode of the SSH&Web Terminal addon
![grafik](https://user-images.githubusercontent.com/7093321/218233297-cea1f6c6-7696-4894-879a-d7e9a899e99d.png)
2. find the container id for "addon_core_configurator" by  command
 `docker container ls`
![grafik](https://user-images.githubusercontent.com/7093321/218233426-264adf8b-9bac-4b5b-b35a-534cedc28166.png)
3. get a bash in the container by 
` docker exec -it CONTAINER_ID bash`
4. change to config directory with
`cd /config/`
5. execute the push once from the console
`git push`

Once the host is confirmed by entering "yes", the push can be executed from the frontend file editor.
Don't forget to enable protection mode again!
