### ISSUE TITLE
Conbee II stick no longer connects after version update 2.12.0

### ISSUE THREAD

**Issue by biiiink** [home-assistant/addons#2069]
## The problem

After updating the version to 2.12.0 in the Phoscon app, the conbee II stick will no longer connect.

## Environment

- Add-on with the issue: deCONZ
- Add-on release with the issue: 6.9.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Home Assistant running in a Proxmox VM

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
[08:59:07] INFO: GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  | DE2234108  | ConBee II 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] novnc.sh: executing... 
[cont-init.d] novnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:59:07] INFO: Running the deCONZ OTA updater...
[08:59:07] INFO: Websockify waiting for VNC to start
[08:59:07] INFO: Running the OSRAM LEdvance OTA updater...
[08:59:07] INFO: Running the IKEA OTA updater...
[08:59:07] INFO: Starting VNC server (local/yes)...
[08:59:07] INFO: Starting websockify...
WebSocket server settings:
  - Listen on 127.0.0.1:5901
  - Flash security policy server
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - proxying from 127.0.0.1:5901 to 127.0.0.1:5900
[08:59:10] INFO: deCONZ waiting for VNC to start
[08:59:10] INFO: Starting the deCONZ gateway...
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[08:59:11] INFO: Starting Nginx...
2021/06/11 08:59:11 [notice] 315#315: using the "epoll" event method
2021/06/11 08:59:11 [notice] 315#315: nginx/1.14.2
2021/06/11 08:59:11 [notice] 315#315: OS: Linux 5.10.42
2021/06/11 08:59:11 [notice] 315#315: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/06/11 08:59:11 [notice] 315#315: start worker processes
2021/06/11 08:59:11 [notice] 315#315: start worker process 1334
08:59:11:213 HTTP Server listen on address 0.0.0.0, port: 40850, root: /usr/share/deCONZ/webapp/
08:59:11:248 COM: use stable device path /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2234108-if00
08:59:11:266 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2234108-if00 / serialno: DE2234108, ConBee II
08:59:11:266 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
08:59:11:311 parent process s6-supervise
08:59:11:311 gw run mode: docker/hassio
08:59:11:311 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
08:59:11:312 DB sqlite version 3.27.2
08:59:11:313 DB PRAGMA page_count: 33
08:59:11:313 DB PRAGMA page_size: 4096
08:59:11:313 DB PRAGMA freelist_count: 0
08:59:11:313 DB file size 135168 bytes, free pages 0
08:59:11:313 DB PRAGMA user_version: 7
08:59:11:313 DB cleanup
08:59:11:313 DB create temporary views
08:59:11:315 started websocket server at port 8081
08:59:11:316 [INFO] - Found file containing button maps. Parsing data...
08:59:11:319 [INFO] - Button maps loaded.
08:59:11:320 dlg action: Read binding table
08:59:11:320 found node plugin: libde_rest_plugin.so - REST API Plugin
08:59:11:321 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
08:59:13:008 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
08:59:13:026 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2234108-if00 / serialno: DE2234108, ConBee II
08:59:13:407 Skip idle timer callback, too early: elapsed 322 msec
08:59:14:046 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2234108-if00 / serialno: DE2234108, ConBee II
08:59:16:847 Announced to internet https://phoscon.de/discover
08:59:25:923 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF
08:59:26:120 device disconnected reason: 5, index: 0
08:59:26:906 wait reconnect 15 seconds
08:59:26:923 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2234108-if00 / serialno: DE2234108, ConBee II
08:59:27:906 wait reconnect 14 seconds
08:59:28:906 wait reconnect 13 seconds
08:59:29:905 wait reconnect 12 seconds
08:59:30:906 wait reconnect 11 seconds
08:59:31:905 wait reconnect 10 seconds
08:59:32:405 start reconnect to network
08:59:32:905 wait reconnect 9 seconds
08:59:33:905 wait reconnect 8 seconds
08:59:34:906 wait reconnect 7 seconds
08:59:35:905 wait reconnect 6 seconds
08:59:36:905 wait reconnect 5 seconds
08:59:37:656 failed to reconnect to network try=1
08:59:37:906 wait reconnect 4 seconds
08:59:38:906 wait reconnect 3 seconds
08:59:39:905 wait reconnect 2 seconds
08:59:40:905 wait reconnect 1 seconds
08:59:40:922 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2234108-if00 / serialno: DE2234108, ConBee II
08:59:42:906 failed to reconnect to network try=2
08:59:47:906 failed to reconnect to network try=3
08:59:52:906 failed to reconnect to network try=4
08:59:52:984 device disconnected reason: 5, index: 0
08:59:53:906 wait reconnect 15 seconds
08:59:53:923 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2234108-if00 / serialno: DE2234108, ConBee II
08:59:54:905 wait reconnect 14 seconds

```

**Comment by biiiink** [comment]
Any help on this would be greatly appreciated

**Comment by biiiink** [comment]
is anyone able to help with this??

**Comment by supersonical** [comment]
I think i have the same issue, i can get it to connect but it doesnt communicate with any devices. I have even tried to factory reset the deconz addon and the decon USB stick. No success.

**Comment by supersonical** [comment]
I have tried everything or everything i  can imagin. Their is no problem with the usb stick Conbee II, worked fine on my ubuntu standalone client but as soon as i connect it to the NUC with HASS OS 6 and the latest version of deconz addon. Nothing happens, i can start the search for lights and switches but nothing is found and the discovery times out.

**Comment by XcOM987** [comment]
I would like to add to this that I am having the “deconz failed to reconnect to network try” error also recently, I have checked the logs, it’s finding the device, it’s locating the firmware and verifying that it’s the latest version.

For some reason some devices connected work, others don’t, and I can’t access the webui, the gateway is grayed out, I checked /dev and the ttyAMA0 was listed, along with ttyACM0, only the AMA one exists in the config area of Deconz, I have restarted HA, and the host, I even did a clean boot, no difference.

I reinstalled deCONZ which resulted in the same issue persisting and the log has the same error, when searching for this error all I can find is issues relating to a VERY old version and the fix was to update to a newer version which is much older than what I have now, some other fixes were to fix the /dev device ID but again this looks correct and the fact I can’t change to anything other than a serial device entry which has never worked, I can’t figure this out for love nor money and am currently resorting to setting up a fresh instance of HA to test deCONZ

**Comment by XcOM987** [comment]
I have managed to replicate the fault with a fresh HA install of HA6.1 and deCONZ 6.9, however if I leave it on the webUI long enough I actually get a second gateway appear which seems to let me login

**Comment by ZeddicPrime** [comment]
Original problem references the Phoscon app, but my original setup didn't use the deConz add-in at all. I didn't install it, and instead used the "Zigbee Home Automation" integration directly. In May and June I was able to sync things just fine and added several Aqara sensors. Since then I believe an HA update broke this - I can't get any new Zigbee devices to add, and some of my existing ones have stopped working. I don't see any log data that indicates any communication is happening at all. I entirely uninstalled the integration but re-adding it doesn't help. I've also tried installing the add-on and using Phoscon which experiences the same problem others are describing above. It's like there's a weird second instance of phoscon. It briefly was able to show me the firmware version, but after a few minutes it could not, and I still can't add devices through the Phoscon interface.
