### ISSUE TITLE
SAMBA Stops working after upgrade to 9.5.1

### ISSUE THREAD

**Issue by Dave-Bryant** [home-assistant/addons#2086]
## Environment

- Add-on with the issue: SAMBA
- Add-on release with the issue: 9.5.1
- Last working add-on release (if known): 9.5.0
- Operating environment (OS/Supervised): hassio

## Problem-relevant configuration

workgroup: WORKGROUP
username: samba
password: *****
allow_hosts:
  - ALL
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false

## Traceback/Error logs

![image](https://user-images.githubusercontent.com/61072520/122663840-c866ec80-d1e0-11eb-91c1-07fc2d585a6d.png)

## Additional information

SAMBA hangs at this point. I would expect the following messages on my log (i.e. this is what I get with 9.5.0).

""
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
waiting for connections
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 10.0.0.55
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 10.0.0.99
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 172.17.0.1
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 10.0.0.55
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 10.0.0.99
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 10.0.0.99
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 10.0.0.99
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 10.0.0.99
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 10.0.0.99
run_elections: >>> Won election for workgroup WORKGROUP on subnet 10.0.0.99 <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 10.0.0.99
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
run_elections: >>> Won election for workgroup WORKGROUP on subnet 172.17.0.1 <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
run_elections: >>> Won election for workgroup WORKGROUP on subnet 172.30.32.1 <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 172.30.32.1
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  authentication for user [samba] -> [samba] -> [samba] succeeded
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
idmap range not specified for domain '*'
desktop-p8shtjj (ipv4:10.0.0.98:18725) connect to service config initially as user root (uid=0, gid=0) (pid 288)
become_local_master_fail2: failed to register name WORKGROUP<1d> on subnet 10.0.0.99. Failed to become a local master browser.
unbecome_local_master_browser: unbecoming local master for workgroup WORKGROUP on subnet 10.0.0.99
standard_fail_register: Failed to register/refresh name WORKGROUP<1d> on subnet 10.0.0.99
*****
Samba name server HASSIO is now a local master browser for workgroup WORKGROUP on subnet 172.17.0.1
*****
*****
Samba name server HASSIO is now a local master browser for workgroup WORKGROUP on subnet 172.30.32.1
*****
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
""

**Comment by cheehuei** [comment]
My Samba also stops working. Please see the screenshot as below. (hope it shows).
![image](https://user-images.githubusercontent.com/48690865/123101705-e8a7dd00-d466-11eb-8f1f-90536cfc0598.png)

**Comment by Dave-Bryant** [comment]
Cheehuei, I think you problem is different to mine and looks to be identical to [here](https://github.com/home-assistant/addons/issues/2081)

**Comment by Soniiiiii** [comment]
> My Samba also stops working. Please see the screenshot as below.
> ![image](https://user-images.githubusercontent.com/48690865/123101705-e8a7dd00-d466-11eb-8f1f-90536cfc0598.png)

https://github.com/home-assistant/addons/issues/2055#issuecomment-854942018

this fix

**Comment by cheehuei** [comment]
> > My Samba also stops working. Please see the screenshot as below.
> > ![image](https://user-images.githubusercontent.com/48690865/123101705-e8a7dd00-d466-11eb-8f1f-90536cfc0598.png)
> 
> [#2055 (comment)](https://github.com/home-assistant/addons/issues/2055#issuecomment-854942018)
> 
> this fix

Thank you very much, Dave and Soniiiii. Yes. the solution fixes my problem!

**Comment by Dave-Bryant** [comment]
Ok now does anyone have any thoughts about my problem, back at the start of this issue.

**Comment by beatyfifty9** [comment]
I'm having same issue. Was working fine until 0.9.1 update.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] samba.sh: executing... 
[23:42:44] INFO: Using hostname=homeassistant interface=eth0
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user homeassistant.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nmbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Registered MSG_REQ_POOL_USAGE
smbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
interpret_interface: Can't find address for eth0
WARNING: no network interfaces found
daemon_status: daemon 'nmbd' : No local IPv4 non-loopback interfaces available, waiting for interface ...
NOTE: NetBIOS name resolution is not supported for Internet Protocol Version 6 (IPv6).
interpret_interface: Can't find address for eth0
WARNING: no network interfaces found
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
open_sockets_smbd: No sockets available to bind to.
===============================================================
INTERNAL ERROR: open_sockets_smbd() failed in pid 270 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 270): open_sockets_smbd() failed in 4.13.8
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern

**Comment by gadget78** [comment]
to help others.. i to was having this issue...
tried the #2055 fix nothing,
reading vlad post [here](https://community.home-assistant.io/t/samba-share-9-5-1-vs-9-3-1-no-access-on-9-5-1/319515/3) worked :)

**go into configuration tab on supervise section.... and completely remove `interface: ‘’`**
as this is throwing off which interface its trying to use, you can specify which one now, but its best to just let it decide by removing this entry!
soon as i removed this line, restarted, it worked :) 

if you go into the log after restart, you can see on 7th line, in green is the hostname, and interface its now using :)
so see if its still not working, see if that tallys up to what it needs to be ! and if still not working you may need to specify !

**Comment by Loents** [comment]
Guys, I constantly get this problem (described below), after updating to version 9.5.1 Samba share stopped working.
Can you tell me what you can do about it.
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 318 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 318): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 319 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 319): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 320 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 320): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 321 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 321): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 322 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 322): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 323 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 323): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 324 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 324): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 325 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 325): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 326 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 326): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 327 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 327): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [sgrodetskiy@gmail.com] -> [sgrodetskiy@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 328 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 328): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Registered MSG_REQ_POOL_USAGE
netbios connect: name1=RASPBERRYPI    0x20 name2=DESKTOP-HFVKG0I0x0
netbios connect: local=raspberrypi remote=desktop-hfvkg0i, name type = 0

**Comment by lmagyar** [comment]
I've created a fork and added back the interfaces functionality, see: https://github.com/home-assistant/addons/issues/2074#issuecomment-1015824912
