### ISSUE TITLE
git pull fails when storing the deploy key with "refusing to work with credential missing host field"

### ISSUE THREAD

**Issue by offbyone** [home-assistant/addons#2242]
## The problem
When configuring the git pull addon, I set up the relevant configuration (I think!) and started the addon. Doing so, however, results in two errors:

* `fatal: refusing to work with credential missing host field`
* `cp: can't stat '/config/*': No such file or directory`

I realize there is nearly a 100% chance I'm holding it wrong, but I can't find anything in the docs I did wrong. The key itself works; I've confirmed that by cloning the repository using it:

```
$ ssh-add -L
<nothing>
$ ssh-add ~/projects/home/hass-config/hass-deploy.sshkey
Identity added: /Users/offby1/projects/home/hass-config/hass-deploy.sshkey (Home assistant deploy key)
$ ssh-add -L
<listed>
$ git clone git@github.com:<redacted>
Cloning into '...'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 34 (delta 0), reused 5 (delta 0), pack-reused 29
Receiving objects: 100% (34/34), 5.31 KiB | 2.65 MiB/s, done.
Resolving deltas: 100% (14/14), done.
$
```

## Environment

- Add-on with the issue: Git Pull
- Add-on release with the issue: 7.13.1
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised): Supervised core-2021.9.7

## Problem-relevant configuration

```yaml
deployment_key:
  - >
    -----BEGIN OPENSSH PRIVATE KEY-----
    <ed25519 key redacted>
    -----END OPENSSH PRIVATE KEY-----
deployment_key_protocol: ed25519
deployment_user: offbyone
deployment_password: ''
git_branch: mainline
git_command: pull
git_remote: origin
git_prune: false
repository: git@github.com:<repo redacted>
auto_restart: false
restart_ignore:
  - ui-lovelace.yaml
  - .gitignore
  - .github
repeat:
  active: false
  interval: 300

```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Check SSH connection
[Warn] No valid SSH connection for git@github.com
[Info] Start adding SSH key
[Info] Setup deployment_key on id_ed25519
[Info] setting up credential.helper for user: offbyone
[Info] Saving git credentials to /tmp/git-credentials
fatal: refusing to work with credential missing host field
[Warn] Git repostory doesn't exist
[Info] Backup configuration to /tmp/config-2021-10-23_11-40-35
cp: can't stat '/config/*': No such file or directory
[Error] Copy files to backup directory failed
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by luthes** [comment]
Ever figure out this issue? Running into it myself, and can't see what's going wrong.

**Comment by offbyone** [comment]
No. I accidentally wiped my HA configuration and never got around to setting this back up again.

**Comment by RawatRicha** [comment]
Not sure if this issue is still open but I would still like to post what helped me resolve a similar issue. 
I configured the private key and SSL certificate to access a GitLab repo in the System Keychains (instead of login- Default Keychains). Once I realised that I have it in the wrong place, I deleted the certificate from the System Keychains (forgetting to delete the key). 
Due to this, I had a broken integration between GitLab and Tower. When I tried to pull (or push) the latest changes to the code, I got this error too- `fatal: refusing to work with credential missing host field` 
I tried pulling the code from Terminal but still got the same error. But I could still access the GitLab repo. I was not sure if this was because of the caching issue in my web browser because I cleared my cache a number of times.
Turned out I had to delete the key from the System keychains. Just to be on a safe side, I exported the key and the certificate (this time in the login- Default Keychains) and everything started working as expected.

Hope this is of some help

**Comment by easybe** [comment]
When using SSH, you can work around the issue by setting `deployment_user = ""` and making sure the user is in the clone URL (the `git@` part). This is not obvious, as the UI does not allow you to do that. So, definitely room for improvement...
