### ISSUE TITLE
Deconz - HA thermostat slider does not update the temperature on Eurotronic Spirit ZigBee

### ISSUE THREAD

**Issue by double1968** [home-assistant/addons#2244]
## The problem

After updating Deconz plugin to version 6.10.0 the thermostat slider
on HA no longer transmits the temperature to the valve
![Cattura](https://user-images.githubusercontent.com/48420012/138611619-c71af7a1-f5ba-4e90-9576-0619de45ce22.PNG)

## Environment

Add-on with the issue: deCONZ
Add-on release with the issue: 6.10.0
Last working add-on release (if known): 6.9.0
Operating environment (OS/Supervised): supervisor-2021.10.6

## Problem-relevant configuration

The problem seems to be due to an incorrect writing in the cluster 0x4003 - Current Temperature Setpoint

![Cattura_2](https://user-images.githubusercontent.com/48420012/138611834-5e791bc2-731f-4896-b19f-230560fec0f0.PNG)
```yaml

```

## Traceback/Error logs

```txt

```

**Comment by bcutter** [comment]
As of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5422 this bug will be fixed with next stable release of deCONZ (it actually is already on beta release channel - but we can't run betas unfortunately).

Next stable release is to be expected for mid of December.

**Hopefully the deCONZ addon for HA will be updated quickly after.** 🙏🏼

**Comment by bcutter** [comment]
Fixed with v2.13.4 of deCONZ shipped with HA addon v6.11.0.

Issue can be closed.
