### ISSUE TITLE
Support management of DDF files through HA config

### ISSUE THREAD

**Issue by supersebbo** [home-assistant/addons#2272]
### Describe the issue you are experiencing

As detailed [here](https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/#goals), deCONZ is moving to a new config model where device definitions are held in DDF json files rather than merged into a core code.  This allows much faster, and user-enabled addition of new device support. 

To provide this capability to HA addon users, the add-on should support mapping the container DDF directory to a HA core config directory (i.e. /config/deconz/devices)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.10.0

### Steps to reproduce the issue

Currently HA Addon users are unable to add custom DDF files as there is no access to the local filesystem.

**Comment by AdrienBigot** [comment]
Hello,

This feature request will be very useful because many device will use DDF Files. Since last version of deCONZ, DDF are enabled by default at boot and I use them for my LiXee Zlinky_TIC module.
See : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5459

The add-on should support mapping the container DDF directory  ~/.local/share/dresden-elektronik/deCONZ/devices/ to a HA core config directory (i.e. /config/deconz/devices)

Thank you in advance.

Adrien

**Comment by ludeeus** [comment]
Please keep this issue tracker to issues, and raise feature requests [on the forum](https://community.home-assistant.io/c/feature-requests/13), thanks 👍

**Comment by AdrienBigot** [comment]
OK, it's done  [here](https://community.home-assistant.io/t/deconz-support-management-of-ddf-files-through-ha-config/370331).

Thank you.
