### ISSUE TITLE
Restart deCONZ addon when it fails

### ISSUE THREAD

**Issue by vlumikero** [home-assistant/addons#2459]
### Describe the issue you are experiencing

The deCONZ addon (or underlying SW/HW) has always been somewhat unstable, and often requires manual restarts. The addon never detects these issues, and just keeps trying to reconnect. The expected behaviour would be that the reconnect works, but since it doesn't, it would make sense for the addon to fail after a number of attempts. Then the watchdog could restart it.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.12.1

### Steps to reproduce the issue

This happens randomly every now and then.

### Anything in the add-on logs that might be useful for us?

```txt
Example of log output, that just goes on forever.


20:35:30:447 start reconnect to network
20:35:30:540 dev /dev/ttyAMA0
20:35:30:637 dev /dev/ttyAMA0
20:35:31:526 dev /dev/ttyAMA0
20:35:31:607 dev /dev/ttyAMA0
20:35:35:521 dev /dev/ttyAMA0
20:35:35:599 dev /dev/ttyAMA0
20:35:35:699 failed to reconnect to network try=1
```

### Additional information

I've submitted this to the deCONZ forum as well, and the response was:

"We don’t maintain the addon. Home assistant maintains it themselves. Your best off to ask there."

https://forum.phoscon.de/t/fail-instead-of-endless-loop/1867

**Comment by mdegat01** [comment]
Hm I'll look at it. Do you know if the deconz app has a health/alive API? If so I can plug that in as the watchdog URL so it can monitor it. Basically just looking for an API that returns a 200 if its alive and anything besides a 200 otherwise.

That being said, you might have a hardware issue? We don't have a lot of reports like this and people would definitely report it if it was. I would try and switching things up to see if you can track down the cause. I'd probably start by switching the USB port and/or the extension cable (if you're using one of those) since those are simple changes. If that doesn't work then perhaps a new stick. Another option is the power cable to the machine, a faulty power cable can cause a whole host of confounding issues like dropped connections. Last resort is the host machine itself but I'd exhaust other options before going there.

**Comment by vlumikero** [comment]
Thanks for the advice. I’ll see if I can switch part by part and see if it
gets better. It doesn’t happen very often, but when it does it’s very
annoying.

I’ll see about the API and see what I can find.
