### ISSUE TITLE
DuckDns addon, cant add WAN ip in yaml config using sensor.ip data

### ISSUE THREAD

**Issue by rizmans** [home-assistant/addons#2487]
### Describe the issue you are experiencing

Because im using 4G internet in Australia the IP that DuckDns detects by default is the wrong IP.

I have setup a Scrape to pull my actual WAN IP from my Router html page, it puts the IP into a sensor called sensor.ip

I need help calling that IP into the Option config IPv4:

Ive tried 
domains:
  - xxx.duckdns.org
token: 01d6d359-a0ab-4795-9ada-4d89d7b703c1
aliases: []
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300
ipv4: sensor.ip

and

ipv4: !include 'sensor.ip'

and

ipv4: !include [sensor.ip]

I really dont know what im doing.. :D 
Any help would be appreciated..

any code i edit in the edit YAML fill under ipv4: gets formatted when saved and has ' placed around it..  
'!include [sensor.ip]'

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

2022.5.3

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[12:17:08] WARNING: 
[12:17:08] INFO: Renew certificate for domains: ohbuoy.duckdns.org and aliases: 
# INFO: Using main config file /data/workdir/config
Processing xxx.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Aug 10 04:31:48 2022 GMT (Longer than 30 days). Skipping renew!
```

**Comment by mdegat01** [comment]
There's no way to do what you're trying to do. You can't use the state of entities in the config of an addon, it's not supported. You're welcome to [feature request](https://community.home-assistant.io/c/feature-requests/13) for it (or PR it if you're comfortable in code).

In the current addon I guess there's three options, none are great:

1) Addon configuration can be updated using Supervisor's REST API ([POST /addons/{addon}/options](https://developers.home-assistant.io/docs/api/supervisor/endpoints#addons)). So theoretically you could make an automation in HA that updates the config of the duck dns addon every time your sensor changes
2) The addon accepts a URL instead of an IP address like <https://api.ipify.org/>. If there's a URL that simply returns the IP address you want and nothing else without authentication you can use that. If you can't find one then it sounds like theoretically you could make one since you have that data available.
3) Make an HA automation that notifies you any time your IP address changes. Update the addon with the new ip address.

**Comment by rizmans** [comment]
Thanks alot for the response and info mdegat01, is very useful for moving forward in the right direction.
