### ISSUE TITLE
HOMEASSISTANT samba host name not connecting

### ISSUE THREAD

**Issue by james28909** [home-assistant/addons#2537]
### Describe the issue you are experiencing

First off all i am here to give a fix for any future readers and hope it will be added to the readme. 

This issue also pertains to windows hyperv home assistant os as well, though it might work for any other os's that have configurable host files!

I was having an issue where for no apparent reason the samba HOMEASSISTANT host name would stop working in file explorer and only the ipv4 address would work for each folder. Well after recreating a few instances of home assistant and trying everything under the sun, i had no joy and it still wouldnt work.

For some reason, i had the bright idea to add ```<home assistants ip>    HOMEASSISTANT``` to my host file in windows and as soon as i tried it it worked flawless. I think the issue might arise from home assistant ip adresses and how windows handles hyperv hostnames or something, i really dont know for sure.

i created 5 different home assistants in hyper v, all of which had a different ip address. samba didnt work for any of them. then i changed the host for one home assistance instance and viola it worked. so i went through the rest of them and added each ip and hostname to the host file and one by one they all started working. 

it has nothing to do with smbv1 or smb2 or smb direct etc, it has to do with a somehow misconfigured or corrupted ip table within windows or either windows samba logic leaves a bit to be desired.

either way if you have the dreaded "Could not connect to HOMEASSISTANT" in file explorer, try this above fix.

hopefully this will be added to the readme

### What type of installation are you running?

Home Assistant - Hyper-V

### Which operating system are you running on?

Fully Updated Windows 11

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

latest 9.7.0

### Steps to reproduce the issue

1.Have a misconfigured windows ip table
2.try to connect to the samba share of home assistant
3. get "Cannot connect to HOMEASSISTANT"
...

### Anything in the Supervisor logs that might be useful for us?

```txt
nope
```

### Anything in the add-on logs that might be useful for us?

```txt
nope
```

### Additional information

operating system windows 11 fully updated with hyperv home assistant

**Comment by mdegat01** [comment]
You followed all the instructions [here](https://www.home-assistant.io/installation/windows#hypervisor-specific-configuration) for Hyper-V right? Particularly the bridged network adapter part?

Also is your router/machine disabling LLMNR or multicast DNS somehow? That's how hostnames actually work on the network. Since it is windows the machine is supposed to be broadcasting that the service is available via LLMNR at your hostname.

Your solution works I guess but the whole benefit of the hostname approach is that the IP address can change but the name still works. That's not true if you've hard-coded it in the hosts file. I'd probably just recommend people use the IP address if the hostname isn't working for some reason personally. Or else check their router and network settings to see what is preventing multicast from working properly.

**Comment by frenck** [comment]
Sorry, missed this one. This user has been banned from our GitHub organization; so he will never respond here, nor will this be "resolved" here.

../Frenck
