### ISSUE TITLE
Private key SSH not possible after the upgrade of ssh add-on

### ISSUE THREAD

**Issue by zigomatichub** [home-assistant/addons#2584]
### Describe the issue you are experiencing

Connection using keys with the add-on is refused to work while it was possible in the previous version..

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.6.0

### Steps to reproduce the issue

Try to connect using a private key using putty (I"m using mobaXterm)

### Anything in the Supervisor logs that might be useful for us?

```txt
no log provided
```

### Anything in the add-on logs that might be useful for us?

```txt
Rollback to previous 9.4 solve the issue
```

**Comment by heckler** [comment]
Actually, there are logs which are relevant to the issue:

```text
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
userauth_pubkey: signature algorithm ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Connection closed by authenticating user root 192.168.6.35 port 51573 [preauth]
```

I didn't find mention on the changelog of anything related to signature algorithms, this might be a bug.

**Comment by snappingneuron** [comment]
Getting this as well. Just to help with trouble shooting, passwordauth works and so does the web GUI

**Comment by mdegat01** [comment]
Right so there was a hidden change here since the apks aren't version-pinned:
https://github.com/home-assistant/addons/blob/902ac2f8992bda9e5317a4f23f65793c2c86d7b4/ssh/Dockerfile#L18

Pulling the image for 9.4 it looks like it had `8.6p1` installed. The new image updated the addon to alpine 3.16 so it pulls the current version of [openssh for 3.16](https://pkgs.alpinelinux.org/packages?name=openssh&branch=v3.16). Which looks like it is `9.0_p1`.

Reviewing the [changelog for OpenSSH](https://www.openssh.com/releasenotes.html) for mentions of RSA between those two releases this jumps out at me from the release notes of version 8.8:

> This release disables RSA signatures using the SHA-1 hash algorithm
> by default. This change has been made as the SHA-1 hash algorithm is
> cryptographically broken, and it is possible to create chosen-prefix
> hash collisions for <USD$50K [1]
> 
> For most users, this change should be invisible and there is
> no need to replace ssh-rsa keys. OpenSSH has supported [RFC8332](https://tools.ietf.org/html/rfc8332)
> RSA/SHA-256/512 signatures since release 7.2 and existing ssh-rsa keys
> will automatically use the stronger algorithm where possible.
> 
> Incompatibility is more likely when connecting to older SSH
> implementations that have not been upgraded or have not closely tracked
> improvements in the SSH protocol. For these cases, it may be necessary
> to selectively re-enable RSA/SHA1 to allow connection and/or user
> authentication via the HostkeyAlgorithms and PubkeyAcceptedAlgorithms
> options. For example, the following stanza in ~/.ssh/config will enable
> RSA/SHA1 for host and user authentication for a single destination host:
> 
>     Host old-host
>         HostkeyAlgorithms +ssh-rsa
> 	PubkeyAcceptedAlgorithms +ssh-rsa
> 
> We recommend enabling RSA/SHA1 only as a stopgap measure until legacy
> implementations can be upgraded or reconfigured with another key type
> (such as ECDSA or Ed25519).

This looks like what you're seeing. If so it looks you will need to generate new keys as the algorithm used was disabled due to a security vulnerability. I can update the changelog to mention it though.

**Comment by jakadia** [comment]
`Unable to negotiate with 192.168.1.85 port 49755: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]`

This is the error I am getting when trying to upload file using the password method.  Any ideas?
