### ISSUE TITLE
Samba share not work

### ISSUE THREAD

**Issue by carbitello** [home-assistant/addons#2616]
### Describe the issue you are experiencing

in config i have a line "inteface: eth0", but i still have error in logs "WARNING: no network interfaces found
interpret_interface: Can't find address for wlan0"
wi fi are deny in system

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

10.0.0

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the add-on logs that might be useful for us?

```txt
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
open_sockets_smbd: No sockets available to bind to.
===============================================================
INTERNAL ERROR: open_sockets_smbd() failed in pid 4062 (4.15.7)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 4062): open_sockets_smbd() failed in 4.15.7
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
[15:07:57] INFO: smbd stopped, restarting...
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
```

**Comment by mdegat01** [comment]
> in config i have a line "inteface: eth0",

This doesn't do anything. There is no `interface` option in the config of this addon anymore, hasn't been for some time.

The addon makes a list of all **supported** network interfaces in the system and binds to all of them. Since you are running a supervised install in an unsupported OS though it's likely that supervisor does not support your primary network interface. In which case this addon won't work for you.

You should consider switching to a supported installation method. Or else you'll need to run your own samba service instead of using this addon.
