### ISSUE TITLE
issue with node-red and port 80

### ISSUE THREAD

**Issue by MiddleSiggy** [home-assistant/addons#2627]
### Describe the issue you are experiencing

It appears that the port value does not work, because you cannot get the service to bind to any port other than 80, which is a problem because node-red also runs on that port. 

It would be nice if the port variable would work, then people could use a different port to allow for the authentication.

I have the same issue with node-red.. it also does not respect the port change.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.16.6

### Steps to reproduce the issue

1. Have node-red installed
2. install LEt's Encrypt..
3. Will not start due to conflict with port 80
...

**Comment by frenck** [comment]
> It appears that the port value does not work, because you cannot get the service to bind to any port other than 80, which is a problem because node-red also runs on that port.

Port 80 as shown in the UI, in that case, is just a visual element that isn't true. This add-on runs on the host network, so the mapping is not really exist. The port number set by the user is picked up and assigned to Node-RED directly.

Port 80 is **not** used by Node-RED by default.

**Comment by mdegat01** [comment]
Just to confirm what Frenck is telling you above, I just installed node red on a test system and its set to use port 1880. I started it then installed Let's Encrypt and immediately ran it - no issues encountered.

Then for good measure I switched Node RED to use port 80. And then switched Let's Encrypt to use port 1880 instead of 80. Again, both started without issue.

So I'm not seeing an issue here. If you have new steps to reproduce please share them.
