### ISSUE TITLE
Mosquitto broker connections "refused: not authorised" following reboot

### ISSUE THREAD

**Issue by chumbazoid** [home-assistant/addons#2680]
### Describe the issue you are experiencing

MQTT clients are unable to connect to Mosquitto broker following host OS reboot, when broker has been set to start on boot.

HA Core logs:
```txt
Logger: homeassistant.components.mqtt.client
Source: components/mqtt/client.py:685
Integration: MQTT (documentation, issues)
First occurred: 1:17:31 PM (5 occurrences)
Last logged: 1:17:47 PM

Disconnected from MQTT server localhost:1883 (5)
 
Logger: homeassistant.components.mqtt.client
Source: components/mqtt/client.py:566
Integration: MQTT (documentation, issues)
First occurred: 1:17:31 PM (5 occurrences)
Last logged: 1:17:47 PM
 
Unable to connect to the MQTT broker: Connection Refused: not authorised.
```

Issue may be worked around by either of the following, after which MQTT connections are restored:
1. Manually restarting broker after HA has fully started
2. Disabling broker start on boot and enabling watchdog

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3

### Steps to reproduce the issue

1. Set Mosquitto broker to start on boot
2. Reboot OS

### Anything in the Supervisor logs that might be useful for us?

Upon initial start of HA:
```txt
22-09-24 13:16:52 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-mosquitto with version 6.1.3
22-09-24 13:16:52 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
22-09-24 13:16:52 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
22-09-24 13:16:58 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /addons/self/options/config
22-09-24 13:17:04 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /discovery
22-09-24 13:17:04 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /services/mqtt
22-09-24 13:17:31 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /auth
22-09-24 13:22:54 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /auth
```
Following manual restart of broker add-on:
```txt
22-09-24 13:24:34 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_core_mosquitto application
22-09-24 13:24:38 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
22-09-24 13:24:40 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
22-09-24 13:24:44 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
22-09-24 13:25:39 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for '<MQTT username>'
22-09-24 13:25:40 INFO (MainThread) [supervisor.auth] Successful login for '<MQTT username>'
```

### Anything in the add-on logs that might be useful for us?

Upon initial auto-start of broker add-on:
```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
parse error: Expected string key before ':' at line 1, column 4
[13:16:58] ERROR: Unknown HTTP error occured
jq: error (at <stdin>:1): null (null) has no keys
[13:17:00] INFO: SSL is not enabled
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[13:17:02] INFO: Starting NGINX for authentication handling...
[13:17:03] INFO: Starting mosquitto MQTT broker...
2022-09-24 13:17:03: Warning: Mosquitto should not be run as root/administrator.
parse error: Expected string key before ':' at line 1, column 4
[13:17:04] ERROR: Unknown HTTP error occured
[13:17:04] INFO: Successfully send discovery information to Home Assistant.
[13:17:05] INFO: Successfully send service information to the Supervisor.
2022-09-24 13:17:03: mosquitto version 2.0.11 starting
2022-09-24 13:17:03: Config loaded from /etc/mosquitto/mosquitto.conf.
2022-09-24 13:17:03: Loading plugin: /usr/share/mosquitto/go-auth.so
2022-09-24 13:17:03:  ├── Username/password checking enabled.
2022-09-24 13:17:03:  ├── TLS-PSK checking enabled.
2022-09-24 13:17:03:  └── Extended authentication not enabled.
2022-09-24 13:17:03: Opening ipv4 listen socket on port 1883.
2022-09-24 13:17:03: Opening ipv6 listen socket on port 1883.
2022-09-24 13:17:03: Opening websockets listen socket on port 1884.
2022-09-24 13:17:03: mosquitto version 2.0.11 running
2022-09-24 13:17:03: New connection from 127.0.0.1:46108 on port 1883.
2022-09-24 13:17:03: Client <unknown> closed its connection.
2022-09-24 13:17:31: New connection from 172.30.32.1:53032 on port 1883.
2022-09-24 13:17:31: Client <unknown> disconnected, not authorised.
2022-09-24 13:17:32: New connection from 172.30.32.1:53044 on port 1883.
2022-09-24 13:17:32: Client <unknown> disconnected, not authorised.
2022-09-24 13:17:34: New connection from 172.30.32.1:34972 on port 1883.
2022-09-24 13:17:34: Client <unknown> disconnected, not authorised.
2022-09-24 13:17:38: New connection from 172.30.32.1:34980 on port 1883.
2022-09-24 13:17:38: Client <unknown> disconnected, not authorised.
("New connection / Client <unknown> Disconnected, not authorized" messages continue)
```

Following manual restart of broker add-on:
```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[13:24:42] INFO: SSL is not enabled
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[13:24:43] INFO: Starting NGINX for authentication handling...
[13:24:43] INFO: Starting mosquitto MQTT broker...
2022-09-24 13:24:44: Warning: Mosquitto should not be run as root/administrator.
[13:24:44] INFO: Successfully send discovery information to Home Assistant.
[13:24:45] INFO: Successfully send service information to the Supervisor.
```

### Additional information

Experienced since approx. mid-August and core-2022.8.6.

Same issue as #2618, which was reported from an unsupported OS and is apparently therefore not monitored. Opening this new ticket to affirm issue is also experienced on a supported system.

**Comment by Larosen** [comment]
I encounter the same issue for several months and have to reinstall MQTT regulary to solve the issue for short time.
Mosquitto broker version: 6.1.3
Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2

**Comment by Aljutor** [comment]
Home Assistant 2022.9.7
Supervisor 2022.09.1

Mosquitto broker
Current version: 6.1.3

Broker regularly do not start correctly when HA restarts (and do not accept external connections), manually restarting broker fixes the problem temporary.

**Comment by Larosen** [comment]
> Home Assistant 2022.9.7 Supervisor 2022.09.1
> 
> Mosquitto broker Current version: 6.1.3
> 
> Broker regularly do not start correctly when HA restarts (and do not accept external connections), manually restarting broker fixes the problem temporary.

Same System Versions and the same Issue.
It started with Mosquitto broker 6.0 or even earlier.

**Comment by andyloree** [comment]
Mosquito broker 6.1.3 on HA 2022.9.1-7 same problem on restart.  I have now disabled watchdog and will leave on start.  I am also having problems with the broker randomly refusing connections after a few days from Z2MQTT, which are resolved if I restart the broker.

**Comment by ProfessorFlut** [comment]
I have this issue for a couple of months now on different versions.

**Comment by 4noxx** [comment]
:(

2022-10-05 08:21:22: Client <unknown> disconnected, not authorised.
2022-10-05 08:23:22: New connection from 172.30.32.1:44716 on port 1883.
error: received null username or password for unpwd check

Mosquitto broker
Current version: 6.1.3

Zigbee2MQTT
Current version: 1.28.0-1

**Comment by tingles2233** [comment]
Same issue on my end. 

Mosquito Broker won`t run under watchguard

Installed Version: 6.1.3

Home Assistant 2022.10.0
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221005.0 - latest

**Comment by LaPe63** [comment]
Seems to be working now since latest Core update, enabled both "start on boot" and "watchdog" and no problem after reboot on both my installations:
Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.2
Frontend-version: 20221010.0 - latest

**Comment by chumbazoid** [comment]
Thanks for heads up @LaPe63. Appears resolved to me now, as well. Can close issue if others are seeing similar.

**Comment by francismiles1** [comment]
For what its worth, I recently had this exact problem. Mine most certainly wasnt a network problem, as I could access the tasmota gui, AND it was appearing in the Mosquitto Broker logs:

> 2023-06-24 15:41:31: New connection from 192.168.0.14:51966 on port 1883.
> 2023-06-24 15:41:31: Client taz_dishwasher1 disconnected, not authorised.

What fixed it?: Oddly, I manually typed in all the mqtt credentials many times (and rebooted device). Still no joy. What fixed it was copy-pasting the password from a field in HA to the tasmota gui. Worked. Can't explain why or how. I must have (somehow) entered in an erroneous character, OR my MAC is not playing ball... 

Anyway, its all good now.

**Comment by WMP** [comment]
I’m seeing very similar behavior, but triggered by a Supervisor restart/update rather than a full system reboot.

I’m running Home Assistant OS with the official Mosquitto add-on and default credentials. Whenever the Supervisor restarts (for example during an update), Mosquitto temporarily starts rejecting connections from Home Assistant as “not authorised”. Home Assistant then disables the MQTT integration. A few minutes later, Supervisor logs show a successful auth for user mqtt and MQTT starts working again, but the integration remains disabled and requires a manual reconfigure (without changing any settings).

Relevant versions:
```
Installation method: Home Assistant OS
Core: 2025.8.0
Supervisor: 2026.01.1
Operating System: 16.0
Frontend: 20250806.0

```

<img width="691" height="1536" alt="Image" src="https://github.com/user-attachments/assets/ad1a0a60-4783-4ebf-b00e-e2d859a9eb33" />

<img width="691" height="1536" alt="Image" src="https://github.com/user-attachments/assets/0e05191f-0f67-45c3-916c-3f9486944271" />

<img width="691" height="1536" alt="Image" src="https://github.com/user-attachments/assets/331e219c-bc8c-4abb-a3de-19bf5372bd0c" />

<img width="691" height="1536" alt="Image" src="https://github.com/user-attachments/assets/95e3a5f1-cbe5-49e9-84f7-b3daba52bba7" />

Logs at the time of failure::
```
[Supervisor] 2026-01-16 00:32:47.236 INFO  Found new Supervisor version 2026.01.1, updating
[Supervisor] 2026-01-16 00:32:47.329 INFO  Update Supervisor to version 2026.01.1
[Supervisor] 2026-01-16 00:32:59.931 INFO  Stopping API on 172.30.32.2
[Supervisor] 2026-01-16 00:33:00.037 INFO  Supervisor is down - 0
[Supervisor] 23:33:00 INFO  Supervisor restart after closing
[Supervisor] 2026-01-16 00:33:10.349 INFO  Attaching to Supervisor ... with version 2026.01.1
[Supervisor] 2026-01-16 00:33:10.879 INFO  Starting API on 172.30.32.2
[Supervisor] 2026-01-16 00:33:13.241 INFO  Supervisor is up and running

[HA Core] 00:33:29 failed to receive on socket: [Errno 104] Connection reset by peer
[HA Core] 00:33:29 Error returned from MQTT server: The connection was lost.
[HA Core] 00:33:29 Error returned from MQTT server: The connection was refused.
[HA Core] 00:33:39 Unable to connect to the MQTT broker: Not authorized

[Supervisor] 2026-01-16 00:38:34.288 INFO  Auth request from 'core_mosquitto' for 'mqtt'
[Supervisor] 2026-01-16 00:38:34.514 INFO  Successful login for 'mqtt'

```

**Comment by WMP** [comment]
## Root Cause Analysis

> **Disclaimer:** This analysis was performed by AI (Claude) based on source code review. I have not personally verified all the details.

After digging through the source code, I found the root cause of this issue. The problem occurs due to a race condition between Supervisor restart and MQTT authentication.

### How authentication works

1. When Home Assistant Core connects to Mosquitto, the `go-auth` plugin first checks local password file (`/etc/mosquitto/pw`)
2. If that fails, it falls back to HTTP backend -> NGINX -> Supervisor `/auth` endpoint
3. Supervisor `auth.py` checks:
   - First, the in-memory cache
   - Then, if Home Assistant Core API is available, validates against it
   - **If HA Core API is not available, it returns `cache_hit is True`** - meaning if user is not in cache, auth fails

### The race condition

When Supervisor restarts:

```
T+0s:  Supervisor starts (fresh process, cache loaded from auth.json)
T+3s:  Supervisor API is up
T+10s: HA Core tries to reconnect to MQTT
T+10s: Mosquitto -> go-auth -> Supervisor/auth
T+10s: Supervisor checks: is HA Core API ready? -> NO (still starting)
T+10s: Supervisor checks cache -> user may not be cached or cache miss
T+10s: Supervisor returns False -> HTTP 401 -> Mosquitto returns code 135 "Not authorized"
```

Relevant code in `supervisor/supervisor/auth.py`:

```python
async def check_login(self, addon, username, password) -> bool:
    cache_hit = self._check_cache(username, password)

    if not await self.sys_homeassistant.api.check_api_state():
        _LOGGER.info("Home Assistant not running, checking cache")
        return cache_hit is True  # <- Returns False if not in cache!

    # ... rest of the logic
```

### The key question: Why does go-auth fall back to HTTP backend?

The `homeassistant` user credentials ARE stored in the local password file (`/etc/mosquitto/pw`). The `go-auth` plugin should validate against this file first, without needing to contact Supervisor at all.

If local file authentication worked correctly, Mosquitto would never return code 135 during Supervisor restart, because:
- The password file is static and always available
- No dependency on Supervisor or HA Core API

**Possible reasons why local auth might fail:**
1. Password hash mismatch between what HA Core sends and what is stored in `/etc/mosquitto/pw`
2. The `go-auth` plugin cache (300 seconds) might have cached a failed auth attempt
3. Race condition during Mosquitto addon startup where the password file is not yet fully written

### My workaround

I manually extracted the `homeassistant` user password from the Mosquitto container:

```bash
docker exec addon_core_mosquitto cat /data/system_user.json | jq -r ".homeassistant.password"
```

Then I reconfigured the MQTT integration in Home Assistant with this password. This ensures the credentials match exactly what is in the local password file.

**Note:** I am not sure yet if this workaround fully resolves the issue - I need more time to observe if the problem reoccurs after the next Supervisor restart/update.

### Suggested fix

The root cause seems to be that authentication falls back to HTTP/Supervisor when it should succeed locally. The fix should focus on ensuring local file authentication works reliably:

1. **Mosquitto add-on**: Investigate why `go-auth` falls back to HTTP backend for the `homeassistant` user - the local password file should be authoritative
2. **Supervisor** (`auth.py`): As a fallback, when HA Core API is not available and user is not in cache, consider returning a "temporarily unavailable" response instead of hard "unauthorized" - this would allow the client to retry instead of treating it as permanent failure


@emontnemery  @jbouwh @bdraco  @mdegat01 @agners @pvizeli
