### ISSUE TITLE
 Let's Encrypt does not start on boot after upgrading to Supervisor 2023.06.3

### ISSUE THREAD

**Issue by oopiicaa** [home-assistant/addons#3111]
### Describe the issue you are experiencing

After upgrading Supervisor to 2023.06.3, I'm getting Repair issue for Let's Encrypt add-on:
![image](https://github.com/home-assistant/addons/assets/24246157/ec2e7e9a-0e68-4f83-9c05-4d124b8e2938)

After multiple reboots, I'm still getting this and the add-on does not start on boot:
![image](https://github.com/home-assistant/addons/assets/24246157/e61e0a53-3ee8-4ebb-b95f-af5fe1f0c706)

The add-on does start without problems if ran manually:
![image](https://github.com/home-assistant/addons/assets/24246157/11358882-eb73-438d-9acf-e931006fc330)

Supervisor logs:
![image](https://github.com/home-assistant/addons/assets/24246157/18f3be68-f184-4ca1-9038-b91d69ee3f1b)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.9

### Steps to reproduce the issue

1. Install and configure Let's Encrypt add-on in official add-on store.
2. Upgrade Supervisor to 2023.06.3.
3. Reboot Home Assistant as prompted.
...

## System Information

version | core-2023.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Prague
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4670
Installed Version | 1.32.1
Stage | running
Available Repositories | 1279
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | beta
supervisor_version | supervisor-2023.06.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 10.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (15.0.2), File editor (5.6.0), SQLite Web (3.8.0), NGINX Home Assistant SSL proxy (3.5.0), Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.111.1), WireGuard (0.8.1), Samba share (10.0.2), ESPHome (2023.6.1), Let's Encrypt (4.12.9), Mosquitto broker (6.2.1), EMQX (0.2.10), Zigbee2MQTT (1.31.2-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 8
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19 June 2023 at 15:44
-- | --
current_recorder_run | 23 June 2023 at 08:18
estimated_db_size | 223.24 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.1 (122751c)
-- | --
cloud_online | 5 / 5
local_online | 5 / 5

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.10
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 3

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-23 08:16:07 INFO (MainThread) [supervisor.resolution.fixups.addon_execute_rebuild] Container for addon core_letsencrypt does not exist, it will be rebuilt when started next
23-06-23 08:16:07 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REBUILD - ContextType.ADDON / core_letsencrypt
23-06-23 08:16:07 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.DOCKER_CONFIG - ContextType.ADDON / core_letsencrypt
23-06-23 08:17:09 ERROR (SyncWorker_1) [supervisor.docker.interface] Container addon_core_letsencrypt is not running
23-06-23 08:22:56 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_letsencrypt application
```

**Comment by mdegat01** [comment]
> After multiple reboots, I'm still getting this and the add-on does not start on boot:

Sorry I'm a bit confused, are you clicking submit on the repair or just rebooting the machine? The message isn't telling you to reboot anything. Nor does that fix anything. All you should have to do is click submit and it'll fix the issue. It's a completely internal issue, there will be no impact on you.

I also just tested this for reference and it did fix the issue for me. I did the following steps:
1. Downgraded a system to supervisor `2023.04.1` (before that issue existed)
2. Installed the lets encrypt addon and ran it once
3. Updated supervisor to `2023.06.3`
4. Saw the repair and clicked submit
5. Repair went away and the addon continued working fine

If you're doing something different please let me know and I can try that to reproduce whatever is going on.

Also just an FYI, the Let's Encrypt addon does not run continuously like other addons. When you start it all it does is this:
1. Check if certificate needs to be renewed
2. If so, renew the certificate
3. Stop

If the certificate does not need to be renewed (like in your log above), this entire process takes about 10-15 seconds tops. Then the addon returns to being stopped until the next time it gets started. So when you say "it does not start after boot", are you confirming that in the log or just looking at the page in the UI? Because if you're just looking at the page in the UI then it probably started and stopped again by the time you got to the page in the UI.
