### ISSUE TITLE
Multiprotocol consistently mismatches channels

### ISSUE THREAD

**Issue by Jonathanese** [home-assistant/addons#3124]
### Describe the issue you are experiencing

Addon: Silicon Labs Multiprotocol
Version:  2.2.0
Device: Sonoff Zigbee Dongle-E
Firmware: RCP Multi-Protocol

Every time I set up the SiLabs multiprotocol plugin and integrations, I immediately get an error saying the channels are mismatched. It sets the Zigbee channel to 25, and the Thread channel to 15.

I try to change the Thread channel by running Form on the OTBR page, setting it to 25. This tends to get rid of the error, but I can't pair anything via Matter. It finds the device, connects, generates the credentials, sends the credentials, then checks the connection. And it always fails at that last step, which I assume is a Thread issue because of a new network which perhaps the rest of the system hasn't detected.

I try to change the Zigbee channel, but rather than letting me change it, it says "This is configured by the Multiprotocol addon and must be changed in the hardware page". But there's no hardware page to set this. So it basically configures the channels wrong and prevents me from fixing it.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.2.0

### Steps to reproduce the issue

1. Flash Dongle-E using the online flashing tool. Use the RCP Multiprotocol firmware.
2. Install the Multiprotocol addon. 460kbaud. Software flow control. OTBR enabled. Ports enabled.
3. Point ZHA to the multiprotocol virtual device
4. Thread and OTBR are auto-detected
5. Reboot Home Assistant OS to re-run detection
6. <Mismatched Channel" error usually occurs here as a settings notification>
7. In ZHA configuration, try to change channel. Prompt tells you you can't do so. References a page in "Hardware" that doesn't exist.

**Try matter**
8. Install Matter addon. Autodetected/Auto-Added to integrations.
9. On phone, try to add Nanoleaf A12 bulb.
10. Sequence: Finding Device -> Connecting to device -> Generating Matter Credentials -> Testing connection -> Connection failed

**Try Change Channel**
11. Open OTBR page
12. Go to "Form", and configure network for channel 25 with the name home-assistant. Defaults elsewhere
13. Click "Form"
14. After a bit, or perhaps a refresh,  in the Thread integration -> Configure page, a second home-assistant network shows up with a border router. This time saying channel 25 instead of channel 15. Set this as the preferred network.
15. Retry the matter settings. Same failure condition.
...

### System Health information

Raspberry PI 4
Sonoff Zigbee Dongle-E

**Comment by darkxst** [comment]
When using Home Assistant hardware, either Yellow or SkyConnect, then these devices will show up on the hardware page. This provides a config flow for these devices to setup MultiPAN. I assume the channel migration has been moved there as well. Previously it was possible to just set the channel in ZHA and reset Thread to pickup change). 

Obviously the ZBDongle-E (and other generic dongles that support Multipan RCP) wont show up there, so I am not sure how to access the channel migration now. May need to work out a way to implement this for generic (i.e non HomeAssistant) dongles.

**Comment by agners** [comment]
> When using Home Assistant hardware, either Yellow or SkyConnect, then these devices will show up on the hardware page.

From what I understand this is the only place when using Multiprotocol to change channels now.

@emontnemery thoughts? Do we have a work around/way to get this done for non-SkyConnect/Yellow users?

**Comment by darkxst** [comment]
I tested the SkyConnect integration with the ZBDongle-E (via updated USB filters) , which works well for channel migration. etc.  I wonder if we could generalise this integration to also include support for the ZBDongle-E? However that doesnt really solve it for users of other dongles which lack sufficient USB data for auto-detection (i.e. EasyIot ZB-GW04 and Elelabs etc)

**Comment by pssc** [comment]
I too have this issue zigbee Mqtt is set to channel 22 but no way to set thread which seems to want to use 15 and is conflicting with my wifi bands... as was a fighting with zbmqtt?

**Comment by darkxst** [comment]
I can provide a rudimentry workaround until there is a better solution implemented.

Copy the following folder to `/config/custom_components'
https://github.com/home-assistant/core/tree/dev/homeassistant/components/homeassistant_sky_connect

Update the `manifest.json` with the usb data for zbdongle-E
```
{
  "domain": "homeassistant_sky_connect",
  "name": "Sonoff ZBDongle-E",
  "version": "0.0.1",
  "codeowners": ["@home-assistant/core"],
  "config_flow": true,
  "dependencies": ["hardware", "usb", "homeassistant_hardware"],
  "documentation": "https://www.home-assistant.io/integrations/homeassistant_sky_connect",
  "integration_type": "hardware",
  "usb": [
      {
      "vid": "1A86",
      "pid": "55D4",
      "description": "*sonoff*plus*",
      "known_devices": ["sonoff zigbee dongle plus v2"]
    }
  ]
}
```

You should now get a SkyConnect device show up in the hardware menu and you can use this perform the channel migration

**Comment by agners** [comment]
We'll add a Thread channel change feature in the Thread panel at one point. That will allow manually change the channels on Zigbee and Thread side.

Meanwhile, the API can be accessed internally, you can use `curl` to ask the OpenThread REST API directly to change the channel:

```sh
curl http://core-silabs-multiprotocol:8081/node/dataset/active | \
  jq '.ActiveTimestamp.Seconds = .ActiveTimestamp.Seconds + 1 |
       {
         ActiveDataset: select(.),
         Delay: 30000,
         PendingTimestamp: .ActiveTimestamp
       } | 
       .ActiveDataset.Channel = 20' | \
  curl -X PUT http://core-silabs-multiprotocol:8081/node/dataset/pending -d@-
```

After 30s the pending dataset will be applied. You can watch the delay counting down by getting the pending dataset.

```
curl http://core-silabs-multiprotocol:8081/node/dataset/pending
```

**Comment by darkxst** [comment]
> allow manually change the channels on Zigbee

How do you manually change Zigbee channel though? ZHA no longer allows this when using multiprotocol, and instead refers you to the non-existent hardware integration.

**Comment by pssc** [comment]
> > allow manually change the channels on Zigbee
> 
> How do you manually change Zigbee channel though? ZHA no longer allows this when using multiprotocol, and instead refers you to the non-existent hardware integration.

zigbee2mqtt allows you to set the channel and use multiprotocol.

**Comment by agners** [comment]
> How do you manually change Zigbee channel though? ZHA no longer allows this when using multiprotocol, and instead refers you to the non-existent hardware integration.

Good point, that use case is not covered currently :cry:

**Comment by darkxst** [comment]
> @emontnemery thoughts? Do we have a work around/way to get this done for non-SkyConnect/Yellow users?

I'd be happy to look at implementing a solution for this, but any thoughts on the best way forward to provide access to channel migration in this case?

**Comment by francisp2** [comment]
I want to change the channel too, but move the ZHA channel to the Thread channel, and not move the Thread radio to another channel, as it forms one network with another Thread radio on another device.

**Comment by francisp2** [comment]
Still no solution

**Comment by agners** [comment]
In pure Thread mode you get this option:

![Screenshot from 2023-09-26 09-34-54](https://github.com/home-assistant/addons/assets/34061/7e94f740-e672-4f85-b8c9-838c6fdafb9f)

@francisp2 is this missing/not working in your case?

Typically, with Multiprotocol we coordinate the channel change, in that case it is available through the hardware menu (Settings > System > Hardware > Configure, then "Configure IEEE 802.15.4 radio multiprotocol support"). But if the Zigbee side is not under the control of Home Assistant Core, the above menu should allow channel change, if I am not mistaken.

**Comment by francisp2** [comment]
This I get when I want to change the Zigbee channel, but there is no multiprotocol under hardware. 

![image](https://github.com/home-assistant/addons/assets/52328611/c67964c2-a062-40ac-b2b7-00844f91da91)

Thread changing works, aligning Zigbee with Thread does not.

**Comment by agners** [comment]
Changing channel on the Zigbee side is only possible through the EmberZNet serial protocol (EZSP). From what I understand you are using Zigbee2MQTT? So this needs to be initiated from Z2M...

**Comment by francisp2** [comment]
I only used Zigbee2MQTT to change the Zigbee channel, and then used migrate radio to have the new channel in ZHA

**Comment by agners** [comment]
Ok wait, so I better understand: Your goal is to use Thread and ZHA, and change the channel of both? But there is no way as the hardware config is missing for the hardware you are using, correct?

**Comment by francisp2** [comment]
>But there is no way as the hardware config is missing for the hardware you are using, correct?
correct

**Comment by Onepamopa** [comment]
I haven't been able to get Thread working... I mean - the Nanoleaf app sees HA thread network in settings, but if I try to assign that hetwork to a led strip (currently BT connected) - the "select" menu is empty ....

**Comment by jtbandes** [comment]
Is there any update on a long-term solution for this issue? I just encountered the same problem after following basically the exact same steps as the original report. [This workaround](https://github.com/home-assistant/addons/issues/3124#issuecomment-1630897233) worked for me to change my Thread channel (although I have [not successfully commissioned](https://github.com/orgs/openthread/discussions/9577) any Matter over Thread devices yet so I can't claim that it's definitely working).

Is it a bug that the Thread and ZHA integrations don't let you change the channel when using multiprotocol firmware? And/or, is it a bug that nothing shows up on the Hardware page?

**Comment by laurynas-pliuskys** [comment]
I am also having the same issue, is there a solution being worked on?

**Comment by shoyu63** [comment]
I have the same problem too. No idea to solve it. Thank you for any help.

**Comment by Ston3s** [comment]
Same here

**Comment by radulyz** [comment]
That's the best solution!
Worked perfectly!!!

> I ran into this same issue. Strangely, the channel numbers seem to stay out of sync when reconfigured through Hardware -> Home Assistant SkyConnect (e.g. it starts with Thread/Zigbee at 15/25, then if I reconfigure it to 11 for example, it will switch to 11/15, and so on). Maybe something is done out of order? (e.g. code sets Zigbee to Thread's channel, then configures the new Thread channel)
> 
> The workaround that I came up with was to go to Settings -> Devices & services -> Zigbee Home Automation -> Configure, then click Download Backup. This creates a .json with your current Zigbee settings. Open the file with a text editor, and under network_info you'll find channel - change this to the same channel as the Thread network. Then click Migrate Radio -> Reconfigure the current radio, and Upload a manual backup. Select your modified .json file, and the Zigbee network will be on the correct channel (maybe needs a restart).
> 
> Obviously it'd be nice if it just worked out of the box as intended, but this is a fairly easy workaround. Hope this helps.

**Comment by satmandu** [comment]
Sorry to interrupt, but I have a SkyConnect dongle, which I assume is supposed to be supported for switching channels with multiprotocol...

```
[core-ssh ~]$ lsusb | grep Silicon
Bus 001 Device 006: ID 10c4:ea60 Silicon Labs CP2102N USB to UART Bridge Controller
```

But I don't see the `Settings -> System -> Hardware -> Configure` Option.

![image](https://github.com/home-assistant/addons/assets/1096701/23cfc4d2-35b0-4bf7-9f6e-cf3db58ed398)

Is there some additional step to get the Hardware Configure option to show up?

**Comment by radulyz** [comment]
It's not done through hardware configuration, but integration configuration (config/integrations/integration/thread then configure/change channel and respectively: Settings -> Devices & services -> Zigbee Home Automation -> Configure)

For these to work you do have to have the dual stack configured on the USB device and also installed and configured the Silicon Labs Multiprotocol add-on for the device AND configured ZHA to point to it instead of the USB device directly...

The add-on and configuration are close to this video https://www.youtube.com/watch?v=j6x43lC9TkM
but you may be able to find something more relevant to the SkyConnect USB dongle...

**Comment by digitalresistor** [comment]
I have two Zigbee networks, with one Thread network:

1. Sonoff E dongle
   - zigbee2mqtt
   - Thread
2. Sonoff P dongle for Zigbee alone (ZHA)

Because there are devices that are better supported by zigbee2mqtt, and then there are devices that work better with ZHA.

- z2m: channel 20
- thread: channel 15 (claimed in the HA interface)
- zha: channel 25

I need to switch Thread to channel 25 to match my Apple Border Routers so I can join them into a single thread network, I may eventually migrate all my ZHA to a different channel so there is no overlap, but for now I can live with the overlap, and I have fewer devices in z2m than in ZHA so re-pairing them isn't as big of a deal.

The web interface won't let me do anything saying that ZHA is on channel 15 (false) and to go to the hardware -> configure (which is non-existent for my setup). I can update the channel to 25 in z2m however the thread channel does not change in HA, and it refuses to join the existing thread network because it still says it is 15.

I tried some of the work-arounds but I don't seem to be getting anywhere. Anyone got any suggestions?

**Comment by vypergts** [comment]
> The web interface won't let me do anything saying that ZHA is on channel 15 (false) and to go to the hardware -> configure (which is non-existent for my setup). I can update the channel to 25 in z2m however the thread channel does not change in HA, and it refuses to join the existing thread network because it still says it is 15.
> 
> I tried some of the work-arounds but I don't seem to be getting anywhere. Anyone got any suggestions?

I'm having this same issue with my Sonoff E dongle with multiprotocol configured and Z2M. Changing the channel to match the Apple network in Z2M doesn't resolve.

**Comment by PaulSD** [comment]
I ran into this same problem, but managed to fix it by deleting the "Thread" and "Open Thread Border Router" integrations, then restarting HA and reconfiguring them.

More specifics:
* I'm using HA OS in a VM with a ZBDongle-E.
* When I first plugged the radio in with the OEM firmware, HA detected it and offered to configure it with ZHA.  I clicked IGNORE.
* I used https://github.com/darkxst/multipan_flasher to flash the MultiPAN firmware.
* After flashing the firmware, I installed the "Silicon Labs Multiprotocol" add-on.  The "Open Thread Border Router" and "Thread" integrations were automatically configured on channel 15.
* I then configured the ZHA integration, which automatically selected channel 25.
* If I tried to change the channel in the ZHA integration config, I got a popup that said: "Multiprotocol addon in use" "Zigbee and Thread share the same radio and must use the same channel. Change the channel of both networks by reconfiguring multiprotocol from the hardware menu."
* If I tried to change the channel in the Thread integration config, I got a popup that said: "The Thread radio has multiprotocol enabled" "To change channel when the Thread radio has multiprotocol enabled, please use the hardware settings menu."
* Trying "Reset border router" in the Thread integration config didn't help; Thread still used channel 15 after the reset.
* Rebooting HA OS didn't help.
* I deleted the Thread integration, then deleted the Open Thread Border Router integration, then restarted HA (I did not reboot the OS).
* After restarting, the Open Thread Border Router integration was automatically configured.  The Thread integration was detected but not auto-configured.  I clicked the CONFIGURE button in the detected integration to reconfigure it.
* After that, both ZHA and Thread were using channel 25.
* I'm still having trouble adding Thread devices to HA, but I think that is due to other issues not related to this - The radio, Multiprotocol add-on, and OTBR all appear to be functioning properly on channel 25.

**Comment by darkxst** [comment]
You should be able to change the Thread channel using the instructions in https://github.com/home-assistant/addons/issues/3124#issuecomment-1630897233

**Comment by darkxst** [comment]
Once the 4.4.0 firmwares are available, devices using EFR32MG21 should be able to support Zigbee and Thread on separate channels.

```
A new feature called Concurrent Listening allows the Zigbee and Thread stacks to operate on independent 802.15.4 channels when used
with the 802.15.4 RCP. This feature works on xG21 and xG24 parts only.


It functions by using the RX antenna diversity hardware block to switch extremely rapidly between two channels, approximately every
48 µsec. If a preamble is detected, it stays on the channel until completion of the packet. Because the switching is so rapid, packets on
either channel are received. When enabling the concurrent listening feature the PHY performance is slightly degraded. The sensitivity of
the IEEE 802.15.4 PHY in this mode drops to around -98 dBm for both the xG21 and xG24.
No configuration is required to enable concurrent listening. It is enabled automatically for the RCP image when built for xG21 or xG24.


The host stacks can select any 802.15.4 channels independently and do not need to coordinate with each other. If they do use the same
channel, then the rapid switching is not used and there is no sensitivity degradation.
```

**Comment by baldisos** [comment]
> We'll add a Thread channel change feature in the Thread panel at one point. That will allow manually change the channels on Zigbee and Thread side.
> 
> Meanwhile, the API can be accessed internally, you can use `curl` to ask the OpenThread REST API directly to change the channel:
> 
> ```shell
> curl http://core-silabs-multiprotocol:8081/node/dataset/active | \
>   jq '.ActiveTimestamp.Seconds = .ActiveTimestamp.Seconds + 1 |
>        {
>          ActiveDataset: select(.),
>          Delay: 30000,
>          PendingTimestamp: .ActiveTimestamp
>        } | 
>        .ActiveDataset.Channel = 20' | \
>   curl -X PUT http://core-silabs-multiprotocol:8081/node/dataset/pending -d@-
> ```
> 
> After 30s the pending dataset will be applied. You can watch the delay counting down by getting the pending dataset.
> 
> ```
> curl http://core-silabs-multiprotocol:8081/node/dataset/pending
> ```

I can't seem to get this running.
When executed, all i get back is a 404.
Is there something i'm doing wrong here?

![grafik](https://github.com/home-assistant/addons/assets/76702976/6bbeffb0-9b14-4a06-924f-c42f9ac37739)

**Comment by darkxst** [comment]
> I can't seem to get this running

`core-silabs-multiprotocol` is an internal dns name only available within HA, so you need to run these commands in a HA terminal/ssh.

**Comment by baldisos** [comment]
Weird. I ran this through the Terminal addon:
![grafik](https://github.com/home-assistant/addons/assets/76702976/cbe83996-f479-4f97-87f0-0c7ea6ac4b48)

I also exposed the API port:
![grafik](https://github.com/home-assistant/addons/assets/76702976/516789f1-31e4-4e7c-a972-4ec5170e419e)

Still it only gives back a 400 Bad Request.

**Comment by Splurch** [comment]
Just adding that I'm having the same problem using a Sonoff Dongle E and being unable to change the radio frequency. Changing the channel in the ZHA backup as per [calwip](https://github.com/calwip) worked but I couldn't get the curl command to work to change the Thread channel (or trying to get the Sonoff to show up in hardware using the skyconnect info) which I need to do to match up with my other border routers. Going to look into using separate radios for Zigby/Thread and am pretty frustrated overall. Would be nice if the documentation or error messages mentioned that there's no easy way to change channels unless you're using Skyconnect or HA Yellow.

**Comment by ronschaeffer** [comment]
> The workaround that I came up with was to go to Settings -> Devices & services -> Zigbee Home Automation -> Configure, then click Download Backup. This creates a .json with your current Zigbee settings. Open the file with a text editor, and under network_info you'll find channel - change this to the same channel as the Thread network. Then click Migrate Radio -> Reconfigure the current radio, and Upload a manual backup. Select your modified .json file, and the Zigbee network will be on the correct channel (maybe needs a restart).
> 

Thanks. This worked to change the ZHA channel, but none of my devices are available. They still show in the device list as per the backup. Is it normal that I would need ot re-pair them or something after the channel change? If that's not normal, any suggestions?

**Comment by ronschaeffer** [comment]
> Thanks. This worked to change the ZHA channel, but none of my Zigbee devices are now available. They still show in the device list as per the backup. Is it normal that I would need ot re-pair them or something after the channel change? If that's not normal, any suggestions?
> 
> (I don't have any Matter devices yet.)
> 
> I have tried multuple restarts. I have also tried following the @calwip method with the original channel number in ordert to (I thought) restore the network as-was, albeit with the channel mismatch.

This (magically?) fixed itself. I manuall restored the backup with the original channel of 15 then restored again with channel 25, and all of the devices reappeared.

**Comment by LookedPath** [comment]
> We'll add a Thread channel change feature in the Thread panel at one point. That will allow manually change the channels on Zigbee and Thread side.
> 
> Meanwhile, the API can be accessed internally, you can use `curl` to ask the OpenThread REST API directly to change the channel:
> 
> ```shell
> curl http://core-silabs-multiprotocol:8081/node/dataset/active | \
>   jq '.ActiveTimestamp.Seconds = .ActiveTimestamp.Seconds + 1 |
>        {
>          ActiveDataset: select(.),
>          Delay: 30000,
>          PendingTimestamp: .ActiveTimestamp
>        } | 
>        .ActiveDataset.Channel = 20' | \
>   curl -X PUT http://core-silabs-multiprotocol:8081/node/dataset/pending -d@-
> ```
> 
> After 30s the pending dataset will be applied. You can watch the delay counting down by getting the pending dataset.
> 
> ```
> curl http://core-silabs-multiprotocol:8081/node/dataset/pending
> ```


I'm currently using the Sonoff Dongle E with the multiprotocol add-on.
I want to setup the OTBR add-on but I don't seem to be having any luck with it.
Knowing that Zigbee and Thread had to use the same channel I used the curl call to set the Thread channel to 25, which is the same channel I have configured in Z2M.

Now when I try to add the OTBR as the default, Home Assistant complains that there's a mismatch between ZHA's channel and Thread's channel.
Since I've never used ZHA I don't understand from where it's pulling the channel value.
![image](https://github.com/home-assistant/addons/assets/2457111/6795cd5d-e8bc-409a-9cf1-6955e0507941)

Is there any way around this?

**Comment by cristianriseri** [comment]
I think I found a way, finally

in ZHA i did a config backup, I modified the json file set the channel = 15, reload the config of ZHA manually and after restart HA. HA told me that the backup loaded was different instead of the previous configuration loaded, I went on loading the new config (the backup modified) and the a new error came up. I did a new restart of HA and all went on
