### ISSUE TITLE
silabs_multiprotocol: Z2M broken after upgrading to 2.4.0

### ISSUE THREAD

**Issue by n-prat** [home-assistant/addons#3386]
### Describe the issue you are experiencing

See https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/555

```
[13:29:31] INFO: Preparing to start...
[13:29:31] INFO: Socat not enabled
[13:29:32] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info 2024-01-05 13:29:34: Logging to console and directory: '/config/zigbee2mqtt/log/2024-01-05.13-29-34' filename: log.txt
Zigbee2MQTT:info 2024-01-05 13:29:34: Starting Zigbee2MQTT version 1.35.0 (commit #unknown)
Zigbee2MQTT:info 2024-01-05 13:29:34: Starting zigbee-herdsman (0.30.0)
Assertion failed: Command (setConfigurationValue) returned unexpected state: [object Object]
Assertion failed: Command (setValue) returned unexpected state: 55
Error: {"address":0,"clusterId":32770,"sequence":2} after 10000ms
at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
at listOnTimeout (node:internal/timers:569:17)
at processTimers (node:internal/timers:512:7)
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.4.0

### Steps to reproduce the issue

1. Upgrade Core,OS,Z2M
2. Check everything is OK
3. Upgrade SiLabs to 2.4.0
4. ZM2 can't start anymore
...

## System Information

version | core-2024.1.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.70-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1372
Downloaded Repositories | 7
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 5.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Silicon Labs Multiprotocol (2.3.2), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.0-1), Duck DNS (1.15.0), Terminal & SSH (9.8.1), File editor (5.7.0), Let's Encrypt (5.0.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 3, 2024 at 9:27 AM
-- | --
current_recorder_run | January 5, 2024 at 4:26 PM
estimated_db_size | 27.47 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Additional information

NOTE: I've reverted to 2.3.2 version so I can't really provide logs; If really needed I will upgrade again but this is not easy b/c breaking all lights and having to restore backups is not really practical.

**Comment by kwstump** [comment]
I also experienced this same error today when going to 2.4.0.  Restoring back to 2.3.2 brought everything back online

**Comment by agners** [comment]
From my tests with ZHA the add-on's Zigbee side is working fine in general. But with the update the add-on comes with the latest Zigbee/EmberZNet SDK, so maybe this trips Zigbee2MQTT :thinking: 

See also https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/555#issuecomment-1879001333.

**Comment by puddly** [comment]
This is fixed by https://github.com/home-assistant/addons/pull/3388 but will break once the addon is updated once more.

**Comment by kwstump** [comment]
Looks like Z2M was updated and seems to again be working after both were updated

**Comment by puddly** [comment]
The addon was downgraded. It'll be upgraded again in a few days so please disable auto updates and manually install them.

Using it with Z2M isn't really a tested configuration.

**Comment by Nerivec** [comment]
@puddly After reading this and the thread in Z2M addon repo... Not sure how HA<>addons update handling is done, but could perhaps a check be introduced so as to abort auto-update on the silabs addon in case [GECKO_SDK_VERSION](https://github.com/home-assistant/addons/blob/6e118fa92a9f1ed8644b58111c53712b9300bb48/silabs-multiprotocol/build.yaml#L8) changed? Otherwise, I'm guessing this will happen again in the future for any install using older HA core version, or using Z2M and with auto-update ON for silabs. As for the user issuing a manual update without checking compatibility first... well... can only post a big warning in the release notes, that's about it, I guess.

**Comment by puddly** [comment]
I don't believe there's a way for an addon to control its own auto-updates, unfortunately. The addon is stopped, the new version is installed, and it starts up. By then, it's too late.

Future updates of the addon will always be compatible with HA Core: if you use ZHA, it will always work with the latest release. Similarly, it shouldn't break older installs because the addon won't update on the old version of Core. Z2M is just in a difficult spot because we have no way to prevent updates of one addon depending on the version of another addon (and we also don't know what version will introduce compatibility).

**Comment by Nerivec** [comment]
> I don't believe there's a way for an addon to control its own auto-updates, unfortunately. The addon is stopped, the new version is installed, and it starts up. By then, it's too late.

I was afraid of that. Would probably be a good addition to HA though, even if it is a simple list of conditions that should pass before the addon is stopped for update.
