### ISSUE TITLE
Mosquitto error: received null username or password for unpwd check

### ISSUE THREAD

**Issue by kapabel** [home-assistant/addons#3614]
### Describe the issue you are experiencing

Mosquitto doesn't let connect any MQTT client with the Home Assistant credentials.
I then have created a dedicated MQTT username with password but it still doesn’t let me connect.
Username and password are each longer than 8 characters.
Passwords and username are 100% correct.
What could I try?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.4.0

### Steps to reproduce the issue

1. create new user
2. Install Mosquitto
3. Install MQTT
4. Enter the user and password
5. Look in the logs

### System Health information

No repairs available. 

### Anything in the add-on logs that might be useful for us?

```txt
2024-05-26 18:31:24: New connection from 192.168.0.107:41261 on port 1883.
error: received null username or password for unpwd check
2024-05-26 18:31:24: Client CLIENTNAME disconnected, not authorised.
```

**Comment by kapabel** [comment]
I already tried to reinstall a fresh system including my backup but the error persists.

**Comment by gfn256** [comment]
Not sure why you've complicated things. Try the following:

1. Enter HA with your **_regular_** user/password (Administrator rights)
2. Install MQTT addon
3. Setup MQTT addon configuration & enter a User & Password (can be same as above 1. or different) & start Addon
4. Enter that User & Password (3. above) in any MQTT devices that you wish the broker to be able to communicate with. 

So for instance whatever device that is at `192.168.0.107`, make sure its got that User & Password (& port) entered correctly in its MQTT settings (as 4. above)

**Comment by kapabel** [comment]
I just downloaded a fresh copy of Home Assistant OS and installed it on a new SD card. I have done nothing to the system besides installing the Mosquitto ad on and creating a new user. It was not working either and I get the same error. Can someone confirm this behaviour ?

**Comment by kapabel** [comment]
The sd card of the security camera was corrupted. I restarted everything and everywhere and for some unknown reason it works now. Once I was able to flash a new firmware it all started to work.

**Comment by jonasnyquist** [comment]
Hi all!

I just want to put it out there, what was my problem (which I spent I don't know HOW many hours troubleshooting... but at least 10-15 hours, easy...), and it was like many times before, really not that complicated of an error once I got down to it...

I'm running a RPi 4 with Home Assistant OS 14.1 (latest updates to Supervisor and Core etc.), and I have been "half-a**ing" it for a couple of years with an external Fibaro Z-Wave controller which I have been integrating with the official integration, and I have also used a Sonoff WiFi-to-Zigbee device as Zigbee controller, using "serial-over-IP" configuration for serial port, integrated using Zigbee2mqtt and it's been "working". 

Full disclosure, I'm very well versed in networks and communications etc, I have been working in the IT industry since mid-90's, so I know my way around most kind of IT systems, but I'm not really a "coder", and likewise, I haven't been working with containers to the extent that I would have liked to call myself "knowledgable" regarding that.

So, I decided that I would scrap the "Integrated 3rd party" solutions, such as the Sonoff "Serial-over-WiFi" Zigbee solution and the Fibaro integrated Z-Wave controller and go for a "proper, fully supported USB Dongle" solution instead.
The Fibaro Z-Wave integration will be replaced by an Aeotec Gen5+ USB Dongle, and the Sonoff Zigbee "controller" is being replaced by a Nabu Casa SkyConnect USB Dongle, and it will all be using MQTT via the Mosquitto Broker.

During my "migration" attempts, somewhere along the way, I "lost my way" and because I'm not an expert in neither coding nor containers/docker, this became pretty messy and I decided to remove all the "old stuff" and reinstall all the integrations and add-ons, which I did.

After reinstalling everything, I had a lot of issues that prevented the zigbee2mqtt add-on from starting.
There were a bunch of errors, which I mostly found "solutions" for which took me a step closer to a working solution but still new errors appeared until I came to a REALLY stubborn one, and it was that while the zigbee2mqtt add-on started, it ran into problems with connecting to the MQTT Broker with an error that indicated that authentication failed.
I was looking all over, and I uninstalled, reinstalled, went through all configuration and then rinse/repeat...

In the end there were 2 issues, both from me kind of making assumptions regarding certain things during configuration of the different integrations/add-ons, and one of the errors was that I for some reason during my uninstall/reinstall etc, I started using "mqtt_broker" instead of "mqtt_user" (which was what I had named the user that I created in Home Assistant) as username.
So I changed the username from "mqtt_broker" to "mqtt_user" in all places and restarted everything, and  2 integrations/add-ons started logging in successfully after I hade resolved the "wrong username" problem, and they were the Z-Wave2mqtt add-on and the MQTT Integration, but still the Zigbee2mqtt add-on kept on failing authentication, which was very strange, frustrating and more than anything, annoying!!
I was also able to connect using "MQTT Explorer" which is a Mac application for MQTT "investigating", which also indicated that the Mosquitto configuration was correct.

So the "first" error was that I had been using the wrong username, but I still got authentication errors, though I believe they changed ever so slightly but I'm not 100% sure.

After A LOT of reinstalling, going through configuration in the UI as well as in configuration files, and to be honest, I wasn't really understanding the relation between the configuration I do in the UI, and where that is saved because even if the "configuration.yaml" file IS created in "/root/homeassistant/zigbee2mqtt" folder (even when I delete the folder completely between uninstall and reinstall) and in some cases updated when doing settings/changes in the Zigbee2mqtt UI, but it's not 100% consistent, for example, after I had installed and configured the Zigbee2mqtt add-on, the "/root/homeassistant/zigbee2mqtt" folder was created, and inside there were a few files and one was the "configuration.yaml". That file contained, after it was "freshly" created, some configuration data from what I put into the UI configuration tab, but not "all" of the data. For example, in the "configuration.yaml" file, the "password" parameter and password was in there, but not the "username" parameter at all.

I found this very puzzling, and I believe that my inability to understand fully how all different components are interacting with each other was making my troubleshooting more "all over the place".

I know it's on me for not reading everything "letter-by-letter", because then I would have caught this much sooner, But in the end it turned out that in "Mosquitto Broker" and "Zigbee2mqtt", I had to put in, not only the username, but also the ACTUAL parameter for the username, and this is where it all went wrong.

In "Mosquitto Broker", all documentation I have seen shows that the parameter "name" is in fact "username" (it says so both in the "Documentation Tab" in the Mosquitto Broker add-on UI as well as in all blog and support articles that I found.

In Zigbee2mqtt, where I naturally put the same data as I had in the Mosquitto Broker configuration which was "username", it came to show that the CORRECT username "parameter" in Zigbee2mqtt should be "user" and NOT "username".
I came to this realization when I all of a sudden took a closer look in the Zigbee2mqtt Yaml configuration examples in one of of the articles that I found, and then after re-checking in the "official" documentation on "https://www.zigbee2mqtt.io/guide/configuration/mqtt.html", where it collaborated the data from the articles, it was indeed "user" that should be used in Zigbee2mqtt for the username "parameter".

I still thought it was very strange that Zigbee2mqtt was the only one that was failing to authenticate, and so when I went into the configuration for the other Integrations/add-ons to change there as well, I realized that both the "MQTT" Integration as well as the "Z-Wave2mqtt" add-on have the username "parameter" (or attribute) "hardcoded", and you only put the ACTUAL username in there which explains why they were working, because there was no way that I was even ABLE to put the wrong configuration data for that.

But what is also VERY confusing is that BOTH those Integrations/add-ons have the username "parameter/attribute" as "username", and in both the "Z-Wave2mqtt" MQTT configuration (under "Settings" in the actual "Z-Wave JS UI" user interface) as well as in the "MQTT" Integration (in the Integration "CONFIGURE" tab, and then "RE-CONFIGURE MQTT"), the parameter for the username is actually done with a capital U, as in "Username", and in these two cases it's probably not a problem as this is most likely "labels" or "names", and not the actual username "parameter/attribute", which is probably "under the hood" somewhere

Again, this is underlining the importance to understand the relationship between UI configuration and where it's stored, and potential Yaml configuration files in some folder somewhere in "some" filesystem (as it's Docker containers it gets slightly more complicated), and as I have been around for a while, I am REALLY a stickler regarding upper and lower-case letters as it makes a HUGE difference, especially in *nix systems, and this is again where it's of the most importance that all of this must be thoroughly documented and explained, and even more important, the parameters should be named the same in all the different integrations/add-ons, and especially frustrating and confusing was the fact that the Mosquitto Broker was expecting the parameter to be "username", while in Zigbee2mqtt the correct parameter name is supposed to be "user" only.

So in conclusion, the authentication details for MQTT collaboration should be as follows:

Chose a username to use for MQTT communications/authentication, and this username should also be created as an admin user in your HA system under "Settings/People/Users"

In Mosquitto Broker:
username: 'your_username'
password: 'your_password'

In Zigbee2mqtt:
user: 'your_username'
password: 'your_password'

And for MQTT Integration and Z-Wave2mqtt, the username parameter is, as I mentioned previously, "hardcoded" into the add-on codebase which makes it irrelevant what the configuration dialog says, and they say, as I mentioned above, "Username" in both add-ons.
But I suspect that somewhere in the HA server, in some configuration file in some folder, there is also Yaml or equivalent code that specifies the ACTUAL parameter that is "sent" from the add-on to the Mosquitto Broker.

I kind of have to believe that the add-on is actually sending both the "attribute" as well as the "value" of it, eg. "user:  my_username", and not only the value itself, because if that was the case, I shouldn't have had any issues when I DID have "username" configured in Zigbee2mqtt, so that kind of indicates that the Mosquitto Broker is expecting the "pair" of "attribute" and "value" for each of the authentication parameters (username and password), which also SHOULD point to that the MQTT and Z-Wave2mqtt Integrations/add-ons have the username "parameter/attribute" configured "somewhere", right??

Anyway, that's my $0,02

I hope that this post and all my work at least help someone else with similar problems at some point!

Cheers,

/Jonas
